### PR TITLE
clarify project goals

### PR DESCRIPTION
**Pull request by N-R-K**
Took suggestion from https://github.com/nsxiv/nsxiv/pull/150#issuecomment-976090044 .

The note about not promising forwards compatibility with patches is added to `nsxiv-extra`, see: https://github.com/nsxiv/nsxiv-extra/commit/22336eb761e078a346da69bfbf584f4e88810ff0

### CODE REVIEW

**Comment by N-R-K** [comment]
Didn't want to make the readme too long, the word drop-in replacement implies backwards compatibility. And people familiar with suckless software should be aware that previous config.h might be broken on update so don't think there's any need to explicitly sate it.

**Comment by TAAPArthur** [comment]
>And people familiar with suckless software should be aware that previous config.h might be broken on update so don't think 

I've never had the experience of my config file being broken on update... which maybe because the projects were more or less complete/static. I don't mind it being omitted.

**Review by TAAPArthur — APPROVED** [review]

**Comment by N-R-K** [comment]
Typically we're doing 1 approvals for doc changes, but since this is a more meaningful topic, I'll wait 2/3 more days to give others chance to comment/view the changes.

**Comment by OliverLew** [comment]
I will approve, but want to state my concerns here: I would think it's too conservative to keep whatever "feature" sxiv had. Sxiv is not some low-level libraries or command line tools that other programs depends on programmatically (except for CLI arguments, that's something better not broken), nor are the current features proven perfect/complete. We can usually see these end-user level applications changing more or less previous features as long as UX improvement will be worth it.

But if you are determined to do so, I am not against. Personally speaking, nsxiv fits my needs quite well. Also, it will be easier if nsxiv starts to make these changes in the future, rather than make changes now but regret it later.

**Review by OliverLew — APPROVED** [review]

**Comment by N-R-K** [comment]
> I would think it's too conservative to keep whatever "feature" sxiv had. Sxiv is not some low-level libraries or command line tools that other programs depends on programmatically (except for CLI arguments, that's something better not broken), nor are the current features proven perfect/complete. We can usually see these end-user level applications changing more or less previous features as long as UX improvement will be worth it.

I will agree that the point you make are valid.

However people can have different ideas on what a better UX is, and sometimes those ideas are conflicting. By keeping all the default behavior we avoid these conflicts, which I think is more productive way moving forward.

**Comment by N-R-K** [comment]
Currently there's two PRs where we want to change the default/break away from sxiv: #171 and #156 . Should we make exceptions for them? If we do make exceptions, what are the rules for that?

If most people agree to make an exception && there's no strong disagreement, then it should be easy. But what happens if 10 people agree to make an exception but 1 person has strong disagreement? Is one strong disagreement enough to nuke the proposal, or should  the 10 agreement be enough to violate the project scope and make an exception?

Personally, I think this PR would be worthless if we want to make exceptions. Since we'll be back to doing votes or each PR where there's a disagreement. So I'd vote for not making exceptions and _if_ we do want to make exceptions then I think one disagreement should be enough to nuke it.

**Comment by TAAPArthur** [comment]
I wanna argue that #156 is different as the functionality is basically the same... but think that is just bias  and/or the cleaner code talking. 

Not making exceptions seems the safest, but there's probably something to be said about changes that affect ui (zoom levels) vs memory usage (cache size) as changing one won't cause nsxiv to OOM or freeze your system. Think the latter case we should take more care to not break as that has a higher chance of reducing portability by default.

And Just to make sure we are on the same page, the rational to revert zoom levels is because it isn't exactly the same as the array right? Technically users could notice the change. If removing the array resulted in the same end result and it was just a structure change to the config file, we'd be fine with it even if it limited what customization.

**Comment by N-R-K** [comment]
> the rational to revert zoom levels is because it isn't exactly the same as the array right?

More or less yes. The previous zoom defaults (`12.5,  25.0,  50.0,  75.0, 100.0, 150.0, 200.0, 400.0, 800.0`) cannot be replicated via zoom steps, and if someone was running something whacky like https://github.com/nsxiv/nsxiv/pull/156#issuecomment-975173608 that cannot be replicated either.

**Comment by N-R-K** [comment]
The PR's been open for sometimes now. If no one else has any objection then we can merge it tomorrow. This also means we're not going to be making any exceptions since no one objected to that either.

**Pull request merged**
