### PR TITLE
Preparing for v28

### PR DESCRIPTION
**Pull request by N-R-K**
Opening this since no one objected to https://github.com/nsxiv/nsxiv/discussions/119#discussioncomment-1502509 .

We need to wait for these PRs to be resolved first however:

- [x] https://github.com/nsxiv/nsxiv/pull/115
- [x] https://github.com/nsxiv/nsxiv/pull/135
- [x] https://github.com/nsxiv/nsxiv/pull/141
- [x] https://github.com/nsxiv/nsxiv/pull/150
- [x] https://github.com/nsxiv/nsxiv/issues/149
- [x] https://github.com/nsxiv/nsxiv/pull/156
- [x] https://github.com/nsxiv/nsxiv/pull/172
- [x] https://github.com/nsxiv/nsxiv/pull/176
- [x] https://github.com/nsxiv/nsxiv/pull/180
- [x] https://github.com/nsxiv/nsxiv/pull/182

### CODE REVIEW

**Comment by TAAPArthur** [comment]
When we release has no special meaning to me, so I don't really care how frequent it happens. But don't think there was that much done since the last release. Are we planning to just release regularly?

**Comment by N-R-K** [comment]
I think we're ready for release. None of the current open PRs are breaking changes, so removing `v28` from them.

**Comment by XPhyro** [comment]
There are still some unreferenced PRs. I'll fix them on a second pass.

**Comment by N-R-K** [comment]
@XPhyro removed webp leak from the changelog since that leak never made it into a release. See https://github.com/nsxiv/nsxiv/pull/132#issuecomment-951583411

Also for future changelogs, do we want reference the PRs? Feels like it makes reading the (raw) markdown much harder.

**Comment by XPhyro** [comment]
How's the readability if we strictly put the PRs on a new line?

**Comment by N-R-K** [comment]
We can leave it be, reading the changelog in the github webview isn't bad. but if someone wants to read the raw markdown that's where it's a bit cluttered.

Can you see if github markdown has "footnotes" ? that can clean things up quite alot.

**Comment by XPhyro** [comment]
It has. I'll format the changelog.

Should I change the previous version too?

**Comment by N-R-K** [comment]
> It has. I'll format the changelog.
> 
> Should I change the previous version too?

i tried it out. it doesn't quite seem to work though.

How do we feel about just referring to the PR number without adding links?

**Comment by XPhyro** [comment]
Shouldn't really be a problem. Any PR is reachable via `github.com/nsxiv/nsxiv/pull/NUMBER` anyways.

**Comment by XPhyro** [comment]
Also, let's not forget to add a date like the others when merging this.

**Comment by N-R-K** [comment]
> Also, let's not forget to add a date like the others when merging this.

Yeah, good catch.

Should try to figure out what we want to do with zoom though. We can add the hard-coded array back (but keep the new shorter logic) to keep things consistent with sxiv and maintain backwards compatibility.

**Comment by N-R-K** [comment]
We need to revert #77

**Comment by N-R-K** [comment]
Converting to draft, since we need to resolve #150 and #156 first.
(And by "resolve" I mean either merge or reject, depending on what we decide in #148)

**Comment by N-R-K** [comment]
Aright, only #156 is remaining to be resolved now.

**Comment by N-R-K** [comment]
@XPhyro what do you think about unifying the tag and commit msg? Currently release commits read "Stable release..." while tag description is "Release version..."

**Comment by XPhyro** [comment]
> @XPhyro what do you think about unifying the tag and commit msg? Currently release commits read "Stable release..." while tag description is "Release version..."

I think we can go for "Release version..." in both.

**Comment by N-R-K** [comment]
Marking this ready for review since only #180 is remaining, and that's mostly an internal change that won't get into the changelog anyways.

**Comment by XPhyro** [comment]
I believe there is nothing left for v28 now.

**Comment by N-R-K** [comment]
> I believe there is nothing left for v28 now.

Yes we're good to go.

However #182 is just fixing a regression added in #156, it never made it into stable release so shouldn't be added in CHANGELOG. @XPhyro

**Comment by N-R-K** [comment]
For release commit/PR like this, do we go for 2 approval or treat it like typical doc PR and go with 1 approval (&& no disapproval) ?

**Review by eylles — APPROVED** [review]

**Review by mamg22 — APPROVED** [review]

**Comment by WitherCubes** [comment]
Does this PR need 3 reviewers to review?

**Comment by N-R-K** [comment]
> Does this PR need 3 reviewers to review?

No, two is fine.

**Pull request merged**
