### PR TITLE
add config.h option for top statusbar

### PR DESCRIPTION
**Pull request by N-R-K**
Closes: https://github.com/nsxiv/nsxiv/issues/230

---

Didn't test it much. Should also add a keybinding to toggle it. Off for today though, I'll do them tomorrow. In the meanwhile feel free to test this out and see if there's any bugs @explosion-mental

### CODE REVIEW

**Comment by mamg22** [comment]
Did some quick testing, seems to be working, except that in thumbnail mode the bar padding is still added as if it were in the bottom. I'll check what's wrong.

**Comment by explosion-mental** [comment]
I've seen the window height is subtracted to the bh, in win_open and the configureevent function.
Maybe thats one reason? I think its not necessary to do that if the bar in on top of the image.

**Comment by N-R-K** [comment]
>  in thumbnail mode the bar padding is still added as if it were in the bottom. I'll check what's wrong.

Look into the y position on the thumbnail render function. I bet it's just that.

**Comment by mamg22** [comment]
> > in thumbnail mode the bar padding is still added as if it were in the bottom. I'll check what's wrong.
> 
> Look into anything y position related on the thumbnail render function. I bet it's just that.

Yup, that was the issue. Adding a conditional depending on `bar.top` like the one added in image render fixes that.

**Comment by N-R-K** [comment]
@mamg22 you should be able to push the changes into my my_topbar branch, "allow edit by maintainer" is enabled.

**Comment by TAAPArthur** [comment]
The diff looks clean to me. Not sure if I'd support adding a keybinding to toggle though. I feel like toggling the presence of the bar itself would be more useful. I'd vote to to just leave keybindings as they are, but don't have a strong opinion.

**Comment by N-R-K** [comment]
If we assume that changing bar position at runtime isn't a common usecae (i think it's a fair assumption) then not adding a keybinding is fine by me as well.

**Review by mamg22 — APPROVED** [review]

**Comment by N-R-K** [comment]
I feel like if someone wanted to know then they'd figure it out by using github search to find the relevant issue/PR.

But I don't oppose documenting it either. Though I'm not sure where we should add it or how to word it.

---

On the other hand, maybe a better solution is to  add a cli option for topbar as well, which would be fine by me.

**Comment by TAAPArthur** [comment]
>I feel like if someone wanted to know then they'd figure it out by using github search to find the relevant issue/PR.

And what would that tell them. Both are pretty bare. I'd suggest some wording, but I actually don't know what the difference is.

>On the other hand, maybe a better solution is to add a cli option for topbar as well, which would be fine by me.

If I recall correctly, there was opposition to having config vars that could only partially be controlled via the cli. I mean I don't mind, but I feel like this was why disabling the status bar wasn't a config option. We could also just make it an enum and have off/top/bottom and have cli/config options for that.

My main criticism is our choice whether to make something a cli vs a config var seems arbitrary and we should either be consistent or explain why we are consistent.

Also should we guard it under `HAVE_LIBFONTS` since the value won't matter if Xft isn't linked? I know it is just cosmetic but we do so for the fonts/colors right above it so it stands out to me

**Comment by N-R-K** [comment]
I think it had to do with the config option turning the cli flag into a no-op.

> Also should we guard it under `HAVE_LIBFONTS` since the value won't matter if Xft isn't linked?

That seems fair to me.

**Pull request merged**
