### PR TITLE
Cleanup manpage

### LINKED ISSUE #56: Cleanup the manpage
I've noticed that there's a lot of places in the manpage where things are weirdly worded. For example

>   M      Repeat last mark action on all images from the last marked/unmarked up to the current one.

We would like to clean the manpage up and make it more tidy and understandable. This is not a high priority issue, but if anyone is looking to contribute this would be a good place to start.

~~Also note that until first release we're doing everything in the `dev` branch, so please use that instead of master.~~

### PR DESCRIPTION
**Pull request by mamg22**
As indicated in #56, there's some parts of the manpage that need rewording or adding missing parts. This PR currently adds the thumbnail mode mouse bindings, along with some rewording, spelling and consistency fixes.

Marking as draft / work in progress: Need feedback on which other parts could get added or changed.

Closes #56

### CODE REVIEW

**Comment by mamg22** [comment]
Regarding the following, mentioned in the linked issue:

> I've noticed that there's a lot of places in the manpage where things are weirdly worded. For example
>
> > M Repeat last mark action on all images from the last marked/unmarked up to the current one.

I came up with two replacements, but don't think they're good enough to be included in the PR:

> Repeat last mark/unmark on all images starting from the last marked/unmarked image up to the current one.

or

> Mark/unmark all images starting from the last marked/unmarked image up to the
 current one.

**Comment by N-R-K** [comment]
@mamg22 The thumbnail mouse bindings are added to the manpage in #167

**Comment by N-R-K** [comment]
Ported the thumbnail binding documentation over to here as I think this makes more sense.

**Review by N-R-K — APPROVED** [review]
I don't see any other glaring problems. So I'm approving it.

However there's two things I noticed:

* We can add link to our website (https://nsxiv.github.io/nsxiv/) somewhere in the manpage, maybe under the `HOMEPAGE` section.

* Some of the new maintainers are missing from the `CURRENT MAINTAINERS` section and some of the listed maintainers are inactive.

This can be separate PR of it's own, but I would suggest:
1. Adding the missing maintainers.
2. sorting the maintainers based on activity.

The reason for 2 is because if someone doesn't want to open a bug report/send a patch via github and would rather mail it to one of the maintainers, it's better to have active maintainers on the top instead of alphabetical sorting.

**Comment by mamg22** [comment]
@OliverLew, @Ytrewq13, do you want to add your email address to the manpage?

**Comment by OliverLew** [comment]
It's okay for me to have just my name in it.

**Comment by mamg22** [comment]
Could this be merged? It has been a week since I asked if missing maintainers wanted their email in the manpage.

**Comment by N-R-K** [comment]
Since it was just doc change, 1 approval should be fine.

**Pull request merged**
