### PR TITLE
fix: exif orientation on Imlib2 v1.7.5 with jpeg

### PR DESCRIPTION
**Pull request by N-R-K**
since Imlib2 v1.7.5, it is capable of parsing exif data on jpeg files
and auto orienting them. this caused nsxiv to rotate the image twice.

Closes: https://github.com/nsxiv/nsxiv/issues/187

---

I don't have images with exif, so I only tested on the example image attached on #187.

### CODE REVIEW

**Comment by N-R-K** [comment]
One more thing, if someone is one Imlib2 git version the compilation will break for them. Since Imlib2 git version doesn't seem to expose the version related macros in the header file.

**Comment by mamg22** [comment]
I can't compile nsxiv with this PR applied on Fedora 34, which ships Imlib2 1.6.1. The error indicates the version macros are missing.

It seems this will not compile with any version older than 1.7.5, because that same release is the one that [introduces version macros](https://git.enlightenment.org/legacy/imlib2.git/tree/ChangeLog#n12). Maybe check for the existence of the version macros instead, since both changs happen in the same release.

**Review by mamg22 — APPROVED** [review]
Compiles and works fine on Imlib2 < 1.7.5.

Edit: And after faking v1.7.5 by adding `-DIMLIB2_VERSION=1` to `CPPFLAGS`, orientation is correctly applied to anything but jpeg.

**Review by eylles — APPROVED** [review]

**Comment by N-R-K** [comment]
@xalexalex since you're on arch, you should be able to use `nsxiv-git` from the aur now, which should fix the orientation issue.

**Pull request merged**
