### PR TITLE
Fix broken ci and enable higher level optimization

### PR DESCRIPTION
**Pull request by N-R-K**

### CODE REVIEW

**Review by XPhyro — COMMENTED** [review]
Looks good to me but I do not have much experience with CI, so I'll not approve officially.

**Comment by N-R-K** [comment]
> I do not have much experience with CI

Neither do I, just did what the previous broken runs were suggesting.

https://github.com/nsxiv/nsxiv/runs/5228523393?check_suite_focus=true#step:3:61

**Review by TAAPArthur — APPROVED** [review]
Just putting it out there that tcc ignores optimization flags so we still have some coverage with non-optimized code.

**Comment by N-R-K** [comment]
> tcc ignores optimization flags

Yeah, was aware. Which is why I didn't remove them from tcc's CFLAGS since it'll be ignored anyways.

**Pull request merged**
