### PR TITLE
Add colors and fonts to config.h

### PR DESCRIPTION
**Pull request by TAAPArthur**
Adds a set of config vars to controll window fg/bg, bar fg/bg and mark
color. This allows everything that can be done from .Xresources to be
configurable from config.h

This was originally part of #95, but moved to its own PR by request.

### CODE REVIEW

**Comment by N-R-K** [comment]
Listing the possibilities described here https://github.com/nsxiv/nsxiv/pull/95#issuecomment-933994246 for unifying the discussion: 

> To re-iterate we have a problem where currently bar color defaults depend on the window colors such that changing just the window color changes the bar color. The question is should changing just the window color in Xresource change the bar color. We could
> 
>   1. (yes) Keep this behavior and only expose window fg/bk and mark color to in config.h.
> 
>   2. (no)  Add all colors to config.h but additionally expose bar color in config and remove the association with window fg/bg. In other words bar colors won't be affect about by window properties in Xresource (they can still be explicitly set). This is the only option that breaks existing behavior, but this is better behavior in my opinion.
> 
>   3. (yes). Add all colors to config.h but keep xresource behavior the same. So if one uses Xresource, the config values are ignored completely.
> 
>   4. (yes) Add all colors to config.h , but only have Xresource window fg/bk change bar colors if the config values match. So if DEFAULT_WIN_FG == DEFAULT_BAR_FG and DEFAULT_WIN_BG != DEFAULT_BAR_BG, the the Xresource window  properties are X and Y respectively and bar properties aren't set, then bar->fg == X and bar->bg == DEFAULT_BAR_BG != Y.
>   5. (yes) Don't add the new config properties and prevent users from changing the default colors in their config.
> 
> 
> My preference is 1 = 2 > 4 > 3 > 5 which may be (heavily) biased by the fact I don't use Xresource

My preference would be 5 due to the fact that it keeps things simpler. Strongly against 1 because it makes things inconsistent, 4 is a bit messy and 2 (currently what this PR does) somewhat breaks existing behavior.

I'm okay with 3 on a surface level, @TAAPArthur how do think the implementation of 3 would be like?

**Comment by TAAPArthur** [comment]
Yeah wasn't sure whether to source the comment or just link to it... Thanks for the summary. 

I don't think 5 is simpler simply because having to use Xresource is more complicated setting a value in config.h. And while it is a behavior change, was it really a good idea to change bar color when an distinct setting was set? Especially when a user could pretty easily set that field themselves. We already "broke" behavior when we fixed the property names and kinda feel this is in the same vein.

Here is what I'm imaging for (4)
Instead of
```
win_bg = win_res(db, RES_CLASS ".window.background", DEFAULT_WIN_BG);
...
bar_bg = win_res(db, RES_CLASS ".bar.background", DEFAULT_BAR_BG);
```
It would be 
```
win_bg = win_res(db, RES_CLASS ".window.background", DEFAULT_WIN_BG);
...
bar_bg = win_res(db, RES_CLASS ".bar.background", strcmp(DEFAULT_BAR_BG, DEFAULT_WIN_BG) == 0 ? win_bg : DEFAULT_BAR_BG);
```

Oh wait you asked about (3)... It'd be basically  the same thing but instead of the strcmp, it would check to see if `win_bg` was loaded from xresources. Probably determine this but adding a field to `win_res` that returns whether the default value was used or not. So something like

```
bool default_value_used;
win_bg = win_res(db, RES_CLASS ".window.background", DEFAULT_WIN_BG, &default_value_used);
...
bar_bg = win_res(db, RES_CLASS ".bar.background", !default_value_used ? win_bg : DEFAULT_BAR_BG);
```

I kinda think both (3) and (4) are bad but they acheive the goal of not breaking previous behavior while not requiring Xresource to configure colors. But really don't think we should link window fg/bg and bar fg/bg in the first place.

**Comment by TAAPArthur** [comment]
>One more option is doing something like this in config.h

Works for my usecase, but don't think it is the best solution. The 2 options don't have to be mutually exclusive

>Also now that I think about it, what about fonts?

Forgot about fonts. They can be handled the same way. Will update the PR later.

**Comment by eylles** [comment]
I think fonts should be their own PR too, for the sake of order.

**Comment by N-R-K** [comment]
> I think fonts should be their own PR too, for the sake of order.

Renamed the PR, should be fine.

**Comment by N-R-K** [comment]
> Do you think it is good or is it just to not make changes to what arguable works?

Both.

Also if someone wants to avoid Xresources and are compiling from source, they can just change it inside `window.c`. So the goal of avoid Xresouces can be achieved without these changes.

**Comment by N-R-K** [comment]
@XPhyro Are you OK with breaking existing behavior? i.e: https://github.com/nsxiv/nsxiv/pull/115#issuecomment-946713106 https://github.com/nsxiv/nsxiv/pull/115#issuecomment-946719997

**Pull request merged**
