### PR TITLE
Use zoom steps instead of hard-coding levels

### LINKED ISSUE #90: Feature proposal: calculating zoom level with a zoom step instead of hard-coded level array
Calculate the zoom level by current_level * zoom_step for zoom in and current_level / zoom_step for zoom out.

I have already implemented it in my sxiv fork: https://github.com/OliverLew/sxiv/commit/b18a8424c4cf2749e01308b3f77d5ef6bbe3eede. If this looks good, I can try to port it to nsxiv.

Pros:

- It is _relative_ zoom. Now one can zoom from any mode and back to that exact zoom level, e.g., 67% -> 84% -> 67%
- The code is much simpler.
- With only max/min zoom level and a zoom step required, the zoom will be log-uniform, so we can avoid any bad chosen level array.

### PR DESCRIPTION
**Pull request by XPhyro**
Closes #90.

### CODE REVIEW

**Review by N-R-K — CHANGES_REQUESTED** [review]
Did some small cleanup. Overall this looks fine, but there's one problem, *this PR currently breaks <kbd>=</kbd> keybinding*

**Comment by N-R-K** [comment]
One other thing I noticed is that `MIN` and `MAX` are guarded by `#ifndef`s but all the other macros aren't.

**Comment by XPhyro** [comment]
> One other thing I noticed is that `MIN` and `MAX` are guarded by `#ifndef`s but all the other macros aren't.

We could clean up the consistency issues in a dedicated PR among the whole codebase.

**Comment by OliverLew** [comment]
@XPhyro Thanks so much! It was night in my time zone and planned to do it later today.

Also didn't notice breaking the key binding, thanks for fixing that :)

**Comment by N-R-K** [comment]
@XPhyro mirrored what `img_change_gamma` is doing. Imo it's cleaner this way.

**Comment by XPhyro** [comment]
Thought being able to set to something other than 1 might be useful, but I didn't notice `img_change_gamma` was doing this too. Looks good.

**Comment by XPhyro** [comment]
I'm assuming the clarification was reverted because it came later than the `=` commit, so I pushed it again.

**Comment by N-R-K** [comment]
One final thing, should we add some cli flag or keybinding to change `ZOOM_STEP` at run-time?

Imo, we got way too many cli flags already but if we make it a key-binding then users can't use `nsxiv-env` to set a default and would need to build from source if they want to change the default.

**Comment by XPhyro** [comment]
What would the flag be if we add it? `-SsZz` are already used. Shall we engrave it into `-z` like `-z ZOOM:STEP` where `:STEP` is optional?

**Comment by N-R-K** [comment]
> What would the flag be if we add it? `-SsZz` are already used. Shall we engrave it into `-z` like `-z ZOOM:STEP` where `:STEP` is optional?

I thought about that, but what if someone does `-z :1.6`, do we assume the default `1.0` then?

**Comment by XPhyro** [comment]
I think we can just not set ZOOM, the equivalent of what would happen without the flag.

**Comment by N-R-K** [comment]
Seems messy. Let's just keep it a config.h thing.

**Review by N-R-K — APPROVED** [review]

**Comment by XPhyro** [comment]
Reused the code from `-T`, have a look.

**Comment by N-R-K** [comment]
Overall, I'm quite happy with these changes as they simplify the codebase quite a bit. @bakkeby Could you take a look here and give your opinion?

**Comment by N-R-K** [comment]
@XPhyro I'm not sure about the cli flag, feels a bit like unnecessary complexity. I think it's fine just leaving it as a `config.h` option.

**Comment by XPhyro** [comment]
Yeah, I don't think the flag is particularly needed.

Since we already had `-T`, I figured we could just use that. Also, the complexity is contained in option parsing only.

Feel free to keep/revert it, I'm okay with both.

**Comment by N-R-K** [comment]
Don't really have too strong of an opinion, let's wait to hear what bakkeby thinks of it. I'm fine both ways as well.

But if we do add the cli thing, we'll need to update the manpage and `print_usage` too.

**Comment by XPhyro** [comment]
Ping @bakkeby @eylles

**Review by N-R-K — CHANGES_REQUESTED** [review]
There's one more thing that's now broken. `50=` used to set zoom level to 50%, now this binding doesn't work.

**Comment by bakkeby** [comment]
I am having a bit of a hard time picturing a use case where you'd want to change the zoom step on the fly via a command line argument. Maybe we should leave this out until someone comes along saying that this is the killer feature they have been looking for?

**Comment by OliverLew** [comment]
> There's one more thing that's now broken. `50=` used to set zoom level to 50%, now this binding doesn't work.

Have been following the thread, I think that what this commit https://github.com/nsxiv/nsxiv/pull/92/commits/31afbd5bf241013954f95018a999265810bd7340 is trying to fix?

**Comment by N-R-K** [comment]
> I am having a bit of a hard time picturing a use case where you'd want to change the zoom step on the fly via a command line argument. Maybe we should leave this out until someone comes along saying that this is the killer feature they have been looking for?

Yeah, lets drop it.



> Have been following the thread, I think that's what this commit [31afbd5](https://github.com/nsxiv/nsxiv/commit/31afbd5bf241013954f95018a999265810bd7340) is trying to fix?

Not quite. https://github.com/nsxiv/nsxiv/pull/92/commits/016a5788479009e588fc9445e2a8f8c27ecc68db should fix things though.

**Comment by OliverLew** [comment]
Merely my own opinion: considering the symmetric naming of `img_zoom` and `tns_zoom`,the naming of the new function can be improved:
`img_zoom_increment` -> `img_zoom`
`img_zoom` -> `img_zoom_to`

**Comment by N-R-K** [comment]
@XPhyro @eylles  we don't really need to merge master, I find it a bit "un-clean". If there is no conflict then squashing should work without issue, nothing needs to be done. And if there is conflict we should prefer using `rebase` instead of merge.

**Comment by XPhyro** [comment]
There was conflict.

I think rebase is disabled, no?

**Comment by N-R-K** [comment]
> I think rebase is disabled, no?

I meant rebasing locally. But for this, let's leave it be, since we'll be squashing it anyways.

**Review by N-R-K — APPROVED** [review]
Grepped through any thing "zoom" related and I think we handled everything well.

This PR is ready to be merged.

**Review by TAAPArthur — APPROVED** [review]

**Comment by TAAPArthur** [comment]
Tired it out and looks fine too me. Also huge fans of removing arrays (when possible) from the config file in general.

**Comment by N-R-K** [comment]
Github gives original author to whoever opens the PR, fixed it and forced pushed with proper author.

**Comment by OliverLew** [comment]
@N-R-K Could the `img-w` and `img-h` in any circumstances be 0 at the same time (is there any checks elsewhere)? I didn't consider that and it could cause zero division.

**Comment by N-R-K** [comment]
This is where w and h are assigned.

https://github.com/nsxiv/nsxiv/blob/a2339e70fdac1db7453cb008c4e37acdb5468f02/image.c#L480-L481

There's no check for 0, but I don't think a 0 width/height image is a valid image. So we should be good.

**Pull request merged**
