### PR TITLE
New website and script for nsxiv

### PR DESCRIPTION
**Pull request by WitherCubes**
The new website which converts the Readme and Man Page to a website using [lowdown](https://github.com/kristapsdz/lowdown).

Preview:
- [Main page](https://withercubes.github.io/nsxiv)
- [Man Page](https://withercubes.github.io/nsxiv/man)

The CSS for the website is just a basic one stripped from my website, feel free to change it.

### CODE REVIEW

**Comment by N-R-K** [comment]
Since the main page is just the README, I'm not sure if it's needed. Specially since it adds a dep to build it (lowdown).

Also @GRFreire was originally behind the current css, so giving a ping.

**Comment by WitherCubes** [comment]
No problem for me if it merges or not, just wanted to give a PR because many other projects do the same, converts the Readme to html and host it on their website.

**Comment by eylles** [comment]
Well, having a website for visibility ain't a bad idea.

**Comment by N-R-K** [comment]
> Well, having a website for visibility ain't a bad idea.

We *do* have a website though. https://nsxiv.github.io/nsxiv/
This is just turning the readme into a website as well. Which feels a bit redundant since the readme can already be viewed sanely via github.

**Comment by eylles** [comment]
Turning the readme into a website can be a starting point, if you ask me what i would do is "split" it into different sections with a navigation sidebar and a section for tips and tricks taken straight from the nsxiv readme and it's link.

**Comment by N-R-K** [comment]
> for tips and tricks taken straight from the nsxiv readme and it's link.

You mean nsxiv-extra?

Also are you going to be able to do all that in a manner so that it can be generated via a script?

Anyways, I don't really care that much about the website. If you're interested in maintaining it, then feel free to make the calls. Also the `gh-pages` branch doesn't require PR or approvals, so feel free to push to it directly if you want as well.

**Comment by WitherCubes** [comment]
I am not that well versed in shell scripting, I will try to do it all in a shell script.

**Comment by GRFreire** [comment]
I support the idea of having a nice index page generated from README. About the POSIX compliant concern, i dont think is actually a problem, since this script is not meant for users of nsxiv, just the maintainer who is going to update the htmls.

The style.css is actually very nice for the main page, but since the man page share the same style, the new changes kinda makes the readability and visual a little worse comparing to the old man page. I tried to modify a bit the style, and got a result between the original and yours, check it out here https://grfreire.github.io/nsxiv/. (also the [style](https://github.com/GRFreire/nsxiv/blob/gh-pages/style.css)) But that is all personal opinion and not too important, since it is just visuals and I personally wont see this website that much.

---

Apart from that, great work! I've never found a tool like `lowdown` before and now I did, thanks ;)

**Comment by N-R-K** [comment]
Yes the script doesn't need to be POSIX. As long as any of the maintainer has the needed depedancies, it should be fine.

**Comment by WitherCubes** [comment]
@GRFreire The CSS is fantastic, the man page is really readable. Sorry for the use of wrong font for the man page. I will revert the CSS. @N-R-K I will create a script which splits each section of Readme within a couple of days, until then don't merge this PR because if others have any opinion they can share and we can commit it all together.

**Comment by N-R-K** [comment]
Currently the only problem seems to be the new css. If you revert it, I think we can merge this PR. The sidebar and whatnot can be done in later PR.

Since @eylles and @GRFreire showed interest in the website, I'll let them decide what they want to do from here.

**Comment by WitherCubes** [comment]
Ok, I will revert the CSS.

**Comment by eylles** [comment]
for what the script has to do, don't even bother making it posix or shell for that matter, perhaps even a python script could be serviceable for this purpose, i mean perhaps something that takes the approach of reading the readme line per line and adding the corresponding formatting tags depending on the contents sounds like a workable approach, but that's rather beyond the point.

**Comment by WitherCubes** [comment]
For now the man page link would seem like it is broken in my preview of the website, but when the PR is merged, it will lead to the correct man page. @eylles I am comfortable with shell scripting and sed, if someone else wants to change the language of the updating script, I am happy about that. For now, let it be a shell script and we can take care of the sidebar and sectioning the website in a later PR.

**Comment by N-R-K** [comment]
Links to `CONTRIBUTING.md` and `CHANGELOG` are broken [here](https://withercubes.github.io/nsxiv)

**Comment by WitherCubes** [comment]
The reason the `CONTRIBUTING.md` and `CHANGELOG` links are broken because the Readme uses relative paths instead of absolute paths.

**Comment by N-R-K** [comment]
@eylles so what's the verdict? Do you want to merge/maintain this?

If so then we can switch to absolute links in the README which should fix the issue of broken links.

**Comment by eylles** [comment]
Eh i mean the maintenance if this is a non issue as the website is script generated, it is only matter of running the script and pushing changes every release or perhaps every other release of whenever the readme changes

**Comment by WitherCubes** [comment]
If this PR is merged, then there is no need to change relative links to absolute links in the Readme.

**Review by eylles — APPROVED** [review]

**Pull request merged**
