### PR TITLE
Add support for multi-frame images via Imlib2

### PR DESCRIPTION
**Pull request by N-R-K**

### CODE REVIEW

**Comment by N-R-K** [comment]
The PR is currently at a decent position. It can load all the animated `gif` and `webp` I have without any artifacts. Feel free to test it out with imlib2 git (503e852) and report if there's any artifacts or bugs.

**Comment by N-R-K** [comment]
Imlib2 [v1.8.0](https://sourceforge.net/p/enlightenment/mailman/message/37605728/) was released with multi-frame support. There's currently two problems with this PR:

* Transparent background of apng images are loaded as 'black' instead of being transparent. `imlib2_view` is able to deal with it fine however, so I assume this is an error on my end somewhere (not sure where though).
* The loading performance is quite bad. It's especially noticeable when loading image with lots of frames. However thanks to our increased cache size in #184, ***reloading*** multi-frame images is almost instant. I've talked to Kim about the loading performance issue and he was open towards resolving it sometimes later.

I think we can merge this PR once the apng issue is resolved, gif and webp images are loading fine. However we can't really issue deprecation warning for older loader since they have noticeably better performance.

**Comment by N-R-K** [comment]
Hmm, not sure what's going on with the png background tbh. Would appreciate if someone can take a look. I'm probably missing something obvious..

**Comment by N-R-K** [comment]
Current status of this PR:

While the apng issue isn't ideal, I don't think it should block the PR. Currently apng images don't even play, while with the PR it does. So that's a net improvement.

However, I think it's best just to wait until the performance issue is resolved until merging this. As long as the performance issue is there, we can't really make this the default anyways.

And I'm suspecting there might be new API functions for dealing with animated images in a more performant manner. So it's best to wait and let the API cooldown so we don't have to litter the codebase with various `#if`s in order to support multiple imlib2 versions.

**Comment by N-R-K** [comment]
The multi-frame loading performance will take a while to be resolved and is (most likely) going to be done via a new API.

So we have three options here:

1. Merge this and then when newer API comes out support them both via `#ifdef`s
2. Merge this and when newer API comes out, drop support for the current API.
3. Don't merge this and just wait for the newer API.

I'd vote in favor of `3` and against `2`. Not a fan of `1` but not against it either.

Opinions? @TAAPArthur @XPhyro @mamg22

**Comment by XPhyro** [comment]
In favour of 2, not against 3, against 1.

I think 1 would litter the codebase. I don't see an issue with merging a temporary solution. I don't imagine 2 would have any non-internal change (apart from performance), so we would not be breaking backwards compatibility for the user (and we do not guarantee patch compatibility).

**Comment by N-R-K** [comment]
> I don't imagine 2 would have any non-internal change (apart from performance), so we would not be breaking backwards compatibility for the user (and we do not guarantee patch compatibility).

It would break compilation for people who would be using older version of the API and would require upgrading to newer Imlib2 version.

For example, if someone is using imlib2 1.8.0 with `HAVE_IMLIB2_MULTIFRAME=1` and then imlib2 2.0.0 comes out (lets say) which solves the performance issue with a newer API. If we drop the older API then this person won't be able to compile anymore unless he upgrades to latest imlib2 as well (which his distro's repo may not have).

This is pretty much the reason I'm against `2` as it's going to cause needless hassle for people who are compiling from source.

**Comment by XPhyro** [comment]
I didn't consider `HAVE_IMLIB2_MULTIFRAME`, good point. But, I don't think depending on the latest major/minor version is necessarily a bad thing.

- Those who compile from source can turn the feature off. It would be functionally equivalent to waiting.
  - This technically breaks backwards compatibility, but we could stress that the feature implementation is *temporary* or *volatile*.
- Packagers, at least in most packaging systems, can mark imlib2 >= or < 2.0.0 as a dependency depending on the nsxiv version/commit if they choose to have the feature on.

On the contrary:

> it's going to cause needless hassle for people who are compiling from source

I think it's more likely to be a hassle for us. Regardless of how much we stress this is volatile, we'll likely receive issues about it.

So `2` may not be worth after all. My new stance is: in favour of 3, against 1 & 2.

---

By the way, do you have a source for this new API? Is there a planned date/version for it, or a discussion around it?

**Comment by N-R-K** [comment]
> By the way, do you have a source for this new API? Is there a planned date/version for it, or a discussion around it?

Not sure if there's anything public about it, my information comes from conversation I had with Kim regarding [this commit](https://git.enlightenment.org/legacy/imlib2.git/commit/?id=31f093570725a478404753699ed8894a2dd3e76e). In short:

1. Currently the loaders open/close file for loading each frame. This worked fine for single frame images, but turns out to be a problem for multi-frame ones.
2. So Imlib2 will most likely need to cache the file into memory to avoid unnecessary I/O.
3. It's not entirely planned on how this will be tackled, but a newer API which informs imlib2 to cache the file was one of the *likely* (but not guaranteed) options.
4. As for when this will happen, there's no time-frame. Kim wants to deal with `load_from_mem()` first (which we can use for #32) before dealing with the multi-frame issue.

**Comment by mamg22** [comment]
> The multi-frame loading performance will take a while to be resolved and is (most likely) going to be done via a new API.
> 
> So we have three options here:
> 
> 1. Merge this and then when newer API comes out support them both via `#ifdef`s
> 2. Merge this and when newer API comes out, drop support for the current API.
> 3. Don't merge this and just wait for the newer API.

I'm in favor of `3`, slightly against `1` because I think it's still a somewhat viable option, and against `2`.

**Comment by N-R-K** [comment]
>     1. Merge this and then when newer API comes out support them both via `#ifdef`s
> 
>     2. Merge this and when newer API comes out, drop support for the current API.
> 
>     3. Don't merge this and just wait for the newer API.

Actually there's a 4th option that I did not think of, and now that I think of it, it seems like the best option to me:

* Merge it into it's own branch and make it clear in the README it's experimental.

This will allow the branch to be tested by more enthusiastic users and would save us the hassle incase we need to adapt to newer imlib2 api.

We can also add warning for package maintainer not to package this, so regular users won't end up with library issues in case there's a new API.

**Comment by XPhyro** [comment]
> Merge it into it's own branch and make it clear in the README it's experimental.

At that point we could just make it into a patch on nsxiv-extra.

**Comment by TAAPArthur** [comment]
3, 4 (its own branch) or 5 (a patch) all work for me. 4 seems the most practical with the least downside.

**Comment by N-R-K** [comment]
> At that point we could just make it into a patch on nsxiv-extra.

Difference here is that we're planning to merge this to master eventually. And it makes things a bit easier on my end since running the ci on a branch of this repo is less work.

**Comment by N-R-K** [comment]
Merged to `imlib2-multiframe` since there wasn't any objection.

**Pull request merged**
