### PR TITLE
document new -0 option

### PR DESCRIPTION
**Pull request by N-R-K**

### CODE REVIEW

**Review by eylles — APPROVED** [review]

**Comment by XPhyro** [comment]
I think the location should either be at the top or at the bottom as is the standard (see `man xargs`, `man file`, etc.). The `-0` option is related to `-o`, so we can say something like *see this other option*.

The current location breaks the alphabetical assortment, does not conform to the standard and risks being read as `-O`

**Comment by N-R-K** [comment]
@XPhyro Should we just change it in the manpage or in `options.c` as well? I placed it there so we can fall through to `-o` but I guess that's not a big deal and can be hardcoded.

**Comment by XPhyro** [comment]
There is a benefit to having it before `-o` as we can just fall through and not repeat code. So I'm impartial for `options.c`.

**Comment by N-R-K** [comment]
Hardcoding isn't a big deal either, it's just 1 line. Let's go for consistency.

**Review by XPhyro — APPROVED** [review]

**Comment by N-R-K** [comment]
Think we should've squashed the PR. Do you think I should squash and force push @XPhyro ?

**Comment by N-R-K** [comment]
@XPhyro I guess we can leave it be this time. Not that big of a deal.

**Comment by XPhyro** [comment]
Sure. I'll make sure to double-check the commit count in the future :)

**Pull request merged**
