### PR TITLE
allow configuring allowed_modifiers in config.h

### PR DESCRIPTION
**Pull request by N-R-K**
Closes: https://github.com/nsxiv/nsxiv/issues/149
Closes: https://github.com/nsxiv/nsxiv/issues/123

### CODE REVIEW

**Comment by TAAPArthur** [comment]
Don't see the point of re-opening 123 just to close it here.

Also there are a fixed amount of modifier so there is no need to negate the var from ignored to allow. 

But anyways I'm against.

**Comment by N-R-K** [comment]
> Also there are a fixed amount of modifier so there is no need to negate the var from ignored to allow.

Much rather have allow_modifier with 3 entries than ignore_mod with 5

> But anyways I'm against.

So you're okay just breaking all alternate keyboard layout?? If the the answer to this is yes then I'm not even going to bother engaging in this convo any further, because that's just absurd.

**Comment by TAAPArthur** [comment]
>So you're okay just breaking all alternate keyboard layout?? If the the answer to this is yes then I'm not even going to bother engaging in this convo any further, because that's just absurd.

Yes, I don't see it as breaking. I see it as doing exactly what is asked and is standard behavior. An alternative is just ignoring `Mod5Mask` right? That was sufficient for the first issue at least. You can have the opposite problem of someone pressing Mod3 or Mod4 and not expecting nsxiv to react to it. I've said all of this before and don't believe you responded to it then and I don't know how to take the lack of response. This is also why I said it isn't a bug; it is an intended feature. Pretty "these" problems where brought up in the commit message/PR.

But sure label a usecase/problem that you don't have as absurd. Disagreeing is one thing, but simplify invalidating an opposing viewpoint defeats the purpose of discussions.

**Review by eylles — APPROVED** [review]
i'm approving since this solves a stupid problem that we shouldn't even have in the first place, that is keystrokes from symbols of the latin alphabet should be recognized regardless of keyboard layout (primary or secondary)

**Comment by N-R-K** [comment]
> a stupid problem that we shouldn't even have in the first place

Thank you, this summarizes my thoughts on the matter perfectly.

**Comment by TAAPArthur** [comment]
>  An alternative is just ignoring `Mod5Mask` right?

**Comment by N-R-K** [comment]
> That was sufficient for the first issue at least.

Are we just going to wait for new issues to pop up? This keeps things consistent with `sxiv` and if someone wants to use more modifier in his key-binding he can add it to `allowed_modifiers`.

**Comment by mamg22** [comment]
I can confirm this PR fixes the issue from #149, whereas the suggestion in [#149 (comment)](https://github.com/nsxiv/nsxiv/issues/149#issuecomment-955635113) didn't.

**Comment by N-R-K** [comment]
@mamg22 thanks for confirming

**Comment by mamg22** [comment]
FWIW, after checking with `xev`, I don't think that `Mod5Mask` (this one is `0x80`) is the issue here as suggested by @TAAPArthur, but rather some higher bits being set.

If I type a key normally in the main layout without any modifier or lock held, `xev` reports a state of `0x0`, but typing with an alternate layout gives out a state of `0x2000` for the same key. Adding more layouts gives `0x4000` and `0x6000` for the third and fourth (by the way, it seems there's a limit of four keyboard layouts).

My guess is that these higher bits that were not ignored caused it to treat all keys as something totally different.

**Comment by TAAPArthur** [comment]
Wow you are using modifiers greater than the macros defines. [0,7] are "normal" key modifiers. [8,12] are the button masks. The wildcard index is 15. You are hitting remaining states possible with the last 2 bits (which is probably why the limit is of additional keyboards is 3). They state aren't defined inX11/X.h so I had assumed they weren't used and left for possible expansions. The fact they are used and undocumented makes this PR much more valid to me

**Comment by TAAPArthur** [comment]
Also want to correct an earlier statement I made amount "common practice". Don't think one is more standard than others
from [dwm](https://git.suckless.org/dwm/file/dwm.c.html)
```
#define CLEANMASK(mask)         (mask & ~(numlockmask|LockMask) & (ShiftMask|ControlMask|Mod1Mask|Mod2Mask|Mod3Mask|Mod4Mask|Mod5Mask))
```
from [surf](https://git.suckless.org/surf/file/surf.c.html)
```
#define CLEANMASK(mask)         (mask & (MODKEY|GDK_SHIFT_MASK))
```
while [st](https://git.suckless.org/st/file/config.def.h.html) is basically what currently in master
```
static uint ignoremod = Mod2Mask|XK_SWITCH_MOD;
```
where XK_SWITCH_MOD is defined somewhere i n X as `(1<<13|1<<14)`

**Comment by eylles** [comment]
i think the st approach seems the "cleaner" one visually.

**Comment by N-R-K** [comment]
> we could afford to be more liberal and add Mod3Mask|Mod4Mask

At this point I'd rather be equal with `sxiv`. If someone wants those modifiers in his keybindings then we've given him a variable where he can add it in.

**Comment by TAAPArthur** [comment]
So we all now agree we have an issue. 2 votes for the "st" approach and 1 vote for the "surf" approach (current state of PR). @mamg22 since you reported the issue that prompted this do you have an opinion given that either would solve your problem by default.

**Comment by mamg22** [comment]
I don't have any strong preference on either, but I do agree that the "st" approach looks cleaner.

**Comment by TAAPArthur** [comment]
> At this point I'd rather be equal with `sxiv`

Don't want to be rude an update your PR to something you don't seem to be in favor for, but I'll offer to push a commit to switch to `static uint ignore_mask = Mod2Mask|LockMask|XK_SWITCH_MOD;` and define XK_SWITCH_MOD

**Comment by N-R-K** [comment]
i REALLY don't want to deal with anymore keybindings which worked on sxiv to break here. Once again the target audience for this is source users and they now have an easy way to add more modifers.

Why do we need to risk breaking bindings for binary users?

**Comment by N-R-K** [comment]
> `static uint ignore_mask = Mod2Mask|LockMask|XK_SWITCH_MOD;` and define XK_SWITCH_MOD

This "solution" will not work for #123 , you will say "oh, the user can add it to their config.h" . Yes, that's only true if the user is a source user, what if it happens to be a binary user? Do we just tell him to use source `nsixv` while binary `sxiv` worked fine for him? And for what benefit? All so for a feature hes not even going to use??

**Comment by TAAPArthur** [comment]
Typing to fast. Meant to add Mod5Mask to that list too

**Comment by N-R-K** [comment]
> Typing to fast. Meant to add Mod5Mask to that list too

Still does not address the general point I'm trying to make.

> i REALLY don't want to deal with anymore keybindings which worked on sxiv to break here.

> Once again the target audience for this is source users and they now have an easy way to add more modifers. Why is this not enough? Why do we need to risk breaking bindings for binary users?

**Comment by TAAPArthur** [comment]
>Still does not address the general point I'm trying to make.

I addressed the (only) legitimate concern your raised.

>Once again the target audience for this is source users 

This statement isn't true as I've commented many times. It affects stock nsxiv too

**Comment by N-R-K** [comment]
> I keep saying the opposite problem of not wanting sxiv keys to be triggered when pressing a key combo with a mod is a real use case.

That seems to be a very specific usecase which is not worth breaking existing keybindings for.

> 3 of the 4 people in this thread think it is cleaner.

Are they also considering the fact that this may break keybindings on binary `nsxiv` which worked on binary `sxiv` ? @eylles @mamg22

**Comment by N-R-K** [comment]
> Very debatable. I keep saying the opposite problem of not wanting sxiv keys to be triggered when pressing a key combo with a mod is a real use case.

So far, we've gotten 2 defect report on `nsxiv` due to this. I'm sure many more will follow if this makes it into a stable release and binary users upgrade. Do you have any data to back up your use case?

**Comment by TAAPArthur** [comment]
> Are they also considering the fact that this may break keybindings on binary `nsxiv` which worked on binary `sxiv`

Can you describe the case where bindings break? We love to cite suckless software so I've given examples that seem to work for them

>That seems to be a very specific usecase which is not worth breaking existing keybindings for.

Why do you think this. This affects anyone who uses a keyboard driven WM where your modifier of choice probably isn't meant to trigger bindings in any other application

**Comment by N-R-K** [comment]
> This affects anyone who uses a keyboard driven WM where your modifier of choice probably isn't meant to trigger bindings in any other application

That entirely depends on weather the WM forwards the keybinding or not. On `dwm` atleast `super+a` (which i've bound to a specific action) certainly doesn't act as `a` on nsxiv. Which brings me to another question, is your WM not doing that?

**Comment by TAAPArthur** [comment]
>  Do you have any data to back up your use case?

I can only describe the problem and state it happens to me specifically with Mod4. 

> On dwm atleast super+a (which i've bound to a specific action) certainly doesn't act as a on nsxiv. Which brings me to another question, is your WM not doing that?

Ok now restart your wm. I restart with Super+q. When the WM is restarting, it doesn't have the key grab so if you key repeat is high (or your WM takes a while to restart), Super+q could be sent to the application in focus. So if nsxiv was in focus, it just exits which is not expected.

**Comment by TAAPArthur** [comment]
Also for #123, they could have used xmodmap to change their bindings in they were on a binary distro. I don't believe it has to be Mod5. It is Mod1 on [some layouts](https://bbs.archlinux.org/viewtopic.php?id=116266) which would break in both nsxiv and sxiv

**Comment by N-R-K** [comment]
> I can only describe the problem and state it happens to me specifically with Mod4.

I think we've had this conversation before. We can't be treating the project as personal project. It's okay that you've stated you have a problem, in-fact you should've given these examples much earlier. But I don't want to be making potentially breaking changes just to satisfy a personal need.

> Ok now restart your wm. I restart with Super+q. When the WM is restarting, it doesn't have the key grabbed so if you key repeat is high (or your WM takes a while to restart), Super+q could be sent to the application in focus. So if nsxiv was in focus, it just exits which is not expected.

> EDIT
It is also perfectly valid for a WM to passively listen (like we do) or grab the key and propagate the event

Given that `sxiv` has been this way for a while and no one else seems to have a problem, I'd say that this is a specific problem which only you seem to encounter. You now have a config var to fix this problem, and since this is a var and not a define it should work on your static lib usecase as well.

_If we do get issues about others facing the same problem_ then I'd be more open towards re-considering this. As of now I'm not convinced the use-case you describe is a general use-case worth "fixing".

**Comment by TAAPArthur** [comment]
>We can't be treating the project as personal project.

Why are the 2 reported and different issues more valid than what I'm describing. Do you want me to open an issue to? I could dwm doesn't handle the alt keyboard usecase and st doesn't handle the AltGroup why and since I believe those are more popular couldn't I argue that these cases you are siting aren't common. Both of those handle mine.

Like you hear about 3 different issues and I show 3 "suckless" programs that handle them differently and you want to single my use case out as abnormal and that no one hits?

>As of now I'm not convinced the use-case you describe is a general use-case worth "fixing".

It has already been fixed. You are about to break it. There are compromises out there that would make everybody who has voiced an opinion happy -- that is not ignoring Mod4/Mod3

**Comment by TAAPArthur** [comment]
@N-R-K To reiterate, it isn't anything other than bias to label my issue as personal and the other 2 as not. They all seem to be reasonable, reproducible usecases that can all be addressed together. Also this isn't a dictatorship so think we should be more objective when intentionally breaking someone else's usecase. Especially when you are reverting an already approved change.

I've tried to show where the harm is in what you are proposing. Where is the concrete harm in the compromise I've countered with? "There might be problems" isn't convincing especially when there is larger software doing the same thing

**Comment by N-R-K** [comment]
> Why are the 2 reported and different issues more valid than what I'm describing?
> They all seem to be reasonable, reproducible usecases that can all be addressed together.

Those two usecase are things that WORKED on sxiv but not on nsxiv.

> I don't believe your fear that something else will break is justified.

We didn't anticipate the current two breakage either. Maybe you're okay with just waiting until it breaks for someone and he opens an issue because this is something that you benefit from (aka it solves your specific use-case) but I'm not.

> Also this isn't a dictatorship

So far I've only voiced my opinion that this isn't a general enough use-case that warrants breaking away from sxiv and potentially breaking key-bindings. How does that amount to "dictatorship" ?

**Comment by mamg22** [comment]
Honestly, I didn't quite consider breakage (or other things) when I put that comment, sorry for that, but after thinking about it:

Was ok with the ignore approach as long as the required masks were provided in the default config, because I didn't find another problem with it.

**However** after some consideration, I think it could be better to use the approach from this PR, it seems slightly more robust, also solves the problem and didn't find new problems with it either.

**Comment by TAAPArthur** [comment]
>How does that amount to "dictatorship" ?

Not attempting to compromise. Not explaining why some usecases are more important than others and/or why the problem(s) I've described aren't general, but just stating as if it was a fact that they are. I get that your focus is on preserving behavior with sxiv, but that doesn't explain why the examples I've given are only specific to me despite the evidence that they are general problems. Also going against the normal of compromise which we've generally done (or at least attempted to do) when such an obvious solution presents itself. 

>We didn't anticipate the current two breakage either.

I mean we did... I just didn't consider/know about cases where one would actually want to ignore these extra bits by default. There are only 16 bits believe all of them have been looked at now. https://github.com/nsxiv/nsxiv/pull/150#issuecomment-955771751. We know what the entire range of bits do now. We should be able to tell which are safe and would go far to conclude that we know Mod4 is safe (given we both seem to use it and I believe it is standard on most layouts). If you want to argue that someone could have their alt-group key be anything between Mod1 and Mod5, that would be fair. And if they switched Mod4 and Mod5 they would get different behavior between sxiv and nsxiv. Of course that would probably be intention and it would be trivial to switch back. But that's a simple way for us to have mutually exclusive goals without needing to attack the validity of a usecase which is subjective.

**Comment by N-R-K** [comment]
> Not attempting to compromise.

The same could be said about you not wanting to be ok with adding the needed modifers into your `config.h`.

> Not explaining why some usecases are more important than others

I've explained it, atleast 5 times now. And you've described it yourself in this very post

> I get that your focus is on preserving behavior with sxiv

> despite the evidence that they are general problems

Your "evidence" was that different programs are handling it differently. And I've commented on that. https://github.com/nsxiv/nsxiv/pull/150#issuecomment-958651412

Also, none of the 3 examples you gave are forks with the goal of maintaining a legacy program. They can afford to make large sweeping changes and even break things if needed, so citing them as "evidence" is even weaker when you consider this.

**Comment by N-R-K** [comment]
I guess it should be clear by now that you're not willing to accept having to manually add the modifers @TAAPArthur and I'm not convinced that we should be breaking away from `sxiv`.

Unfortunate, but I guess we'll need to settle this on yet another vote. I'm not sure if it's a healthy to do development where things constantly needs voting. And I guess this all goes back to the `evolution` vs `maintain` approach. Might be worth revisiting the idea of a separate repo/branch in #148

**Comment by N-R-K** [comment]
@TAAPArthur Now that we seem to agree that we nsxiv should stay true/close to sxiv, do you still oppose this?

Which also brings me to another question, are you still interested in doing review/approval/feedback or do you not want to participate/be pinged on these as well?

**Comment by TAAPArthur** [comment]
> @TAAPArthur Now that we seem to agree that we nsxiv should stay true/close to sxiv, do you still oppose this?

I was hoping for more people to explicitly express approval and/or for the README to be updated, but anyways I withdraw my main objection. I still think `ignored_mask` is a better name/more descriptive than `allowed_modifiers` since we are ignoring the precedence of the modifiers rather disallowing key events with them. Ones just the negation of the other, so don't think the length of the declaration needs to change

> Which also brings me to another question, are you still interested in doing review/approval/feedback or do you not want to participate/be pinged on these as well?

I'm fine being pinged for reviews. By the way there are only 16 mods so we can reduce the var to an unsigned short.

**Comment by N-R-K** [comment]
Speaking of names, the variable names (excluding arrays) should be all caps. Currently only other var without all caps is `keyhandler_abort`. I'll open a PR fixings that.

**Comment by N-R-K** [comment]
@TAAPArthur  I think the `USED_MODS` name takes care of being more descriptive.

---
As for
> I was hoping for more people to explicitly express approval and/or for the README to be updated

Not sure what to update tbh. Currently we have this in the readme:

> nsxiv is a fork of now unmaintained sxiv with the purpose of maintaining it and adding simple, sensible features.

Which seems to be enough to me. But feel free to suggest something else if you think that's appropriate.

**Comment by TAAPArthur** [comment]
>@TAAPArthur I think the USED_MODS name takes care of being more descriptive.

I see where you are are coming from. `USED_MODS` because only these bits of the modifier are used. I feel like it is one of those things that makes sense only if you are familiar with it and not that confident ignoremask is better (I've seen the latter used more and I prefer it so I'm biased). 

> But feel free to suggest something else if you think that's appropriate.

Thinking something more blunt
```
nsxiv is a fork of now unmaintained sxiv with the purpose of maintaining it and adding small, simple, sensible features. We intend to keep all sxiv's behaviors/features even if removing them would make the code simpler and in general we aim to keep the general code similar (ie no large refactoring). However, there's not guarantee that patches or customization for sxiv will work out of the box.
``

**Comment by N-R-K** [comment]
Opened a PR for the readme/doc changes #89 

As for the name, @XPhyro any suggestions? I feel like `USED_MODS` is fine ¯\\\_(ツ)\_/¯

**Comment by XPhyro** [comment]
I think we should make sure it is conveyed as what it is, a bitmask; but also give the context. So `USED_MODS_MASK` and `IGNORED_MODS_MASK` are okay at first glance.

Looking at the usage of it, I think it makes more sense to explicitly list all used mods rather than think about every single unused one. This would ensure users do not have to research the standard on mods or mitigate unexpected outcomes. So, I think it should be `USED_MODS_MASK`.

I'm taking the liberty to change it, feel free to revert the commit.

**Review by XPhyro — APPROVED** [review]

**Comment by N-R-K** [comment]
I agree, explictly stating it's a mask is fine. Although I'd drop the `S` from `MODS`, it's possible to use a single mod.

**Comment by N-R-K** [comment]
We can maybe even do, `USED_MODMASK` to be consistent with the `MODMASK` macro name. What do you think ? @XPhyro

**Comment by N-R-K** [comment]
> I also think MODMASK is better than USED_MODMASK

That's going to collide with the macro name though.

**Comment by TAAPArthur** [comment]
>That's going to collide with the macro name though.

We could just inline the macro. It is used in like 2 places in one function.

**Comment by N-R-K** [comment]
We could. Not entirely sold if it's worth it though and imo a bit out of scope for this PR.

**Comment by N-R-K** [comment]
Merging this since MODMASK would require a bit more fiddling and 3 people seems to be on-board with USED_MODMASK with no strong objection.

**Pull request merged**
