### PR TITLE
Update to the website

### PR DESCRIPTION
**Pull request by WitherCubes**

### CODE REVIEW

**Comment by N-R-K** [comment]
Don't think we need to update the site on each readme change. Just once per release is fine.

**Comment by WitherCubes** [comment]
I guess this time you can merge this, from next time I will do it once per release.

**Comment by N-R-K** [comment]
We can just leave it as draft until release.

**Comment by N-R-K** [comment]
@WitherCubes Can you run the update script again on the current git master?

**Comment by WitherCubes** [comment]
I will update the website after fixing the version badge.

**Comment by WitherCubes** [comment]
@N-R-K The website has been updated, you can merge it now.

**Review by N-R-K — APPROVED** [review]

**Pull request merged**
