### PR TITLE
README: add related projects and some doc fixes

### PR DESCRIPTION
**Pull request by N-R-K**
Closes: https://github.com/nsxiv/nsxiv/issues/169

### CODE REVIEW

**Comment by N-R-K** [comment]
I'll keep the PR open for a week or two, so the original issue stays open and gets some visibility.

In the meanwhile, feel free to suggest more option or correct the description. @TAAPArthur @explosion-mental

**Comment by explosion-mental** [comment]
@N-R-K I will add [lel](https://git.codemadness.org/lel/) to the list and maybe mention also [farbfeld](https://tools.suckless.org/farbfeld/) format. I'm not a fan of converting images to view them but it's an option, I guess.

**Comment by N-R-K** [comment]
> @N-R-K I would add [lel](https://git.codemadness.org/lel/) to the list and maybe mention also the [farbfeld](https://tools.suckless.org/farbfeld/) format. I'm not a fan of converting images to view them but it's an option, I guess.
> 
> Edit: Also what about `imv` and `qiv`? I would suggest adding headers like **Imlib2 viewers** and/or **Convertion viewers**, etc.

Feel like the README gets a bit crowded that way.

How about we mention suckless rocks at the beginning and then only mention projects which are not included in suckless rocks ?

**Comment by TAAPArthur** [comment]
> How about we mention suckless rocks at the beginning and then only mention projects which are not included in suckless rocks ?

I agree there is little point of repeat the info that is listed there. But for the same argument we could just not change nsxiv's README and just add our projects there instead. Maybe only include those with a similar feature set to sxiv here (including what can be done with a config file). Guess that may be subjective, but I think the workflow for something like feh which is cli driver is different than sxiv which is primary keybinding driven.

**Comment by N-R-K** [comment]
> But for the same argument we could just not change nsxiv's README and just add our projects there instead

I don't think you can just add your project there willy-nilly. Though I'm not sure what the exact qualification are for a project to be added on rocks.

> Guess that may be subjective, but I think the workflow for something like feh which is cli driver is different than sxiv which is primary keybinding driven.

I've never used feh, but afaik it's a minimal viewer. So it's the minimal aspect on which I decided to add it. Although if we just switch to not repeating suckless rocks then we'll just remove feh, so I guess it shouldn't matter.

**Comment by explosion-mental** [comment]
> Feel like the README gets a bit crowded that way. 
>How about we mention suckless rocks at the beginning and then only mention projects which are not included in suckless rocks ?

@N-R-K True. Now I think this section should be as little as the 'see also' section on a man page.

>  Maybe only include those with a similar feature set to sxiv here (including what can be done with a config file).

Disagree on this, I think the purpose of the related proyects is to list similar proyects, in terms of what they are achieving (being image viewers).


Talking about man pages, I give the idea that this could be a one liner, something like:

```markdown
Related Proyects
-----------------------
[div](https://github.com/TAAPArthur/div), [mage](https://github.com/explosion-mental/mage)

More similar projects at <https://suckless.org/rocks>
```

**Comment by N-R-K** [comment]
Man pages are supposed to be manuals, so I don't think listing similar projects in manpage makes sense. Readme is the proper place for it imo.

**Comment by explosion-mental** [comment]
> Man pages are supposed to be manuals, so I don't think listing similar projects in manpage makes sense. Readme is the proper place for it imo.

oh yeah I was just taking man pages as an 'style' example, this should remain on the readme.

**Comment by TAAPArthur** [comment]
I guess I'm thinking of the user who found their way here and wanted some that nsxiv won't provide. I was aiming to give them guidance on similar projects that perhaps are more aligned with their goals. Which is why I was going for something more than just a link. But a link may be fine... when I was searching for a image viewer I just DFS-ed though image viewers starting from suckless' rocks page.

**Comment by N-R-K** [comment]
Thinking back, I think it's probably best to merge it instead. More people see the README compared to issue tracker I'd assume.

Anyhow, I'll still leave it for a day or two in case someone comes up with some other similar project suggestion.

**Review by TAAPArthur — APPROVED** [review]

**Comment by explosion-mental** [comment]
Can the mage description be changed?
```diff
-Aims to be a smaller/more-suckless version of sxiv.
+A smaller/more-suckless version of sxiv.
```
Since I don't aim to get all behaviour of sxiv and the later does explain the current state.

**Comment by N-R-K** [comment]
@XPhyro can you sneak this into #175 when it's ready?

**Pull request merged**
