### PR TITLE
add -0 for outputting null-terminated list

### PR DESCRIPTION
**Pull request by N-R-K**
this doesn't add much, if any, additional complexity to the codebase and
can be quite handy for scripting purposes.

Closes: https://github.com/nsxiv/nsxiv/issues/67

### CODE REVIEW

**Comment by TAAPArthur** [comment]
Don't really object to this, but can't this be done with a shell script by piping into `tr '\n' '\0'`.
This may be in part a response to https://github.com/nsxiv/nsxiv/pull/49#issuecomment-921681857 about where the line is drawn between shell scripts and small patches/easy of use

**Comment by N-R-K** [comment]
> Don't really object to this, but can't this be done with a shell script by piping into `tr '\n' '\0'`.

Not if any of the filenames contain a new-line.

**Comment by TAAPArthur** [comment]
... Is that an actual concern of yours or just theoretical? I'm asking mainly out of curiosity.

The underlying concern is there exists an external tool that can handle 99.9% of cases. Are 6 lines worth the extra .1% given the extra .1% can't be cleanly achieved by an external script. I guess technically one could have a wrapper the effectively removed and re-added (by copying/linking to a temp file) the new lines if one wanted.

I'm more interested in where the line is drawn between patches, wiki entries/shell scripts/external tools and merging upstream. I'd argue that while the patch is simple and harmless, it can basically be done (for most cases) with a shell script and therefore shouldn't be included but made into a wiki entry. Curious how the "(for most cases)" part matters to others

**Comment by N-R-K** [comment]
> Is that an actual concern of yours or just theoretical?

Newlines in files are perfectly valid in the unix world. Only reserved characters are `/` and the nullbyte. https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_169

One might argue that we shouldn't promote people having such absurd filenames and ask them to fix their shit instead, and I'd agree. But I'm simply pointing out that filenames with newline is valid.

**Review by Ytrewq13 — APPROVED** [review]

**Review by XPhyro — APPROVED** [review]

**Pull request merged**
