### PR TITLE
cleanup docs

### PR DESCRIPTION
**Pull request by N-R-K**

### CODE REVIEW

**Review by XPhyro — APPROVED** [review]

**Review by eylles — APPROVED** [review]

**Comment by N-R-K** [comment]
@XPhyro For some reason, the f.a.q link isn't linking properly.
https://github.com/nsxiv/nsxiv#faq

**Comment by XPhyro** [comment]
@N-R-K It is linking properly on my end. What's the problem?

**Comment by N-R-K** [comment]
> @N-R-K It is linking properly on my end. What's the problem?

I meant the last Question, #32 isn't linking.

**Comment by N-R-K** [comment]
This is what I'm seeing.

image

**Comment by XPhyro** [comment]
I thought GitHub is not supposed the link those in the readme, or is it?

To link it, we need a normal hyperlink.

**Comment by N-R-K** [comment]
I see, wasn't aware of that. We should fix it then. Also since it's just a readme change, the `v27` tag can stay where it is. Shouldn't be a problem.

**Comment by eylles** [comment]
it ain't linking for me either, also the ones in the changelog ain't linking either

**Comment by XPhyro** [comment]
I believe the auto-linking only occurs in comments, i.e. issues, PRs, discussions. If that's correct, this is expected behaviour.

I thought this PR wanted consistency with the changelog.

-----

As these are non-essential, we can fix in a new PR as @N-R-K said.

**Pull request merged**
