### PR TITLE
code-style: prefer calloc over malloc+memset && add missing `static`

### PR DESCRIPTION
**Pull request by N-R-K**

### CODE REVIEW

**Comment by XPhyro** [comment]
While testing this PR, I've randomly encountered a crash. Is there a difference between malloc and calloc that we might be missing here (apart from the set to 0 thing)? I can't see any difference in `calloc(3p)` and `malloc(3p)`.

I've encountered it once, and cannot reproduce it, so it just might have been some cosmic rays deciding to bombard my memory.

**Comment by N-R-K** [comment]
> While testing this PR, I've randomly encountered a crash.

What was the error message?

**Comment by XPhyro** [comment]
> What was the error message?

I don't recall an error message.

**Review by mamg22 — APPROVED** [review]
LGTM, got not crashes during tests.

**Pull request merged**
