### PR TITLE
fix: crashing on bad exif thumbnail

### PR DESCRIPTION
**Pull request by N-R-K**
this does not need to be a fatal error.
if im is NULL we're going to load it with imlib2 anyways.

one other problem this solves is that before, due to the fatal error,
the tmpfile opened under /tmp wouldn't get cleaned up.

Closes: https://github.com/nsxiv/nsxiv/issues/69

### CODE REVIEW

**Comment by N-R-K** [comment]
Hmmm, one problem is we don't really know if it's bad exif data causing the failure or if it's allocation failure. Maybe the error message should be more vague...

**Comment by TAAPArthur** [comment]
For the second problem, should we have an `atexit` handler or something to always ensure we cleanup temporary files we create. Outside of a crash a user could politely kill us at any time.

**Comment by N-R-K** [comment]
> should we have an `atexit` handler or something to always

I believe we have it in the main function.

**Comment by eylles** [comment]
> Hmmm, one problem is we don't really know if it's bad exif data causing the failure or if it's an actual allocation failure. Maybe the error message should be more vague...

perhaps make the message "bad data" until we can be sure.

**Comment by N-R-K** [comment]
Maybe libexif has some function to check for bad/corrupted data? If so it would be ideal to check with that instead. I'll look into the docs.

**Review by eylles — APPROVED** [review]
so far i have found no obvious problem testing this so i'm approving it.

**Comment by N-R-K** [comment]
I don't believe this should be merged (yet). If we can detect bad exif data then I'd like to go down that path as I think that's more proper.

But even then, is there any reason to fatally error out there? Later when we try to load thumbnail with `imlib` and it returns `NULL`, we simply return false.

https://github.com/nsxiv/nsxiv/blob/24e70a99e38ba71ac26e8476c5f2d4352c6ff548/thumbs.c#L327-L330

So why are we fatally erroring out here? I think I wanna delve deeper into this before merging.

https://github.com/nsxiv/nsxiv/blob/24e70a99e38ba71ac26e8476c5f2d4352c6ff548/thumbs.c#L313-L316

**Comment by XPhyro** [comment]
I can't reproduce the crash in thumbnail mode, but weirdly, I experience the opposite. It crashes when in image mode 100% of the time even with this PR.

**Comment by N-R-K** [comment]
> I can't reproduce the crash in thumbnail mode, but weirdly, I experience the opposite. It crashes when in image mode 100% of the time even with this PR.

What image are you using? The one in https://github.com/nsxiv/nsxiv/issues/69 ?

**Comment by XPhyro** [comment]
I thought I was, but no. I probably got this image from one of the other issues, but don't know which. Here it is:

1x1-000000ff

Here's the [link](https://user-images.githubusercontent.com/10392678/134080295-c76880b0-8afd-4882-a9a8-de0f3730b661.png) if you can't see the image. It's a bit small.

**Comment by N-R-K** [comment]
>     * The image I uploaded only crashes if I switch to it in the positive direction (i.e. Space by default)

Now I can reproduce. I opened a separate issue for that. https://github.com/nsxiv/nsxiv/issues/82

- - -

Back on topic: 

> I could not get a crash with the Thumbnail mode crashes: cannot allocate memory #69 image in any case.

It happens only on thumbnail mode. Did you try that? @XPhyro

**Comment by XPhyro** [comment]
> It happens only on thumbnail mode. Did you try that? @XPhyro

Yes. No crash in image or thumbnail modes.

**Comment by N-R-K** [comment]
> Yes. No crash in image or thumbnail modes.

Interesting... Anyways, I don't see much reason to fatally error out here. I think we can merge this PR as is.

**Comment by XPhyro** [comment]
> I think we can merge this PR as is.

If it solves the crash for you, definitely.

**Comment by N-R-K** [comment]
@XPhyro Any reason for not approving?

**Review by XPhyro — APPROVED** [review]

**Pull request merged**
