### PR TITLE
Revert "fix: out-of-bounds access when bg not in color map"

### PR DESCRIPTION
**Pull request by N-R-K**
with this patch certain gif images will fail to play. one other problem
here is that it suddenly breaks the loop without free-ing data and rows,
leading to a memory leak.

regardless, this needs to be investigated further.

here's an example image where this happens:
https://i.postimg.cc/SQf1TJJg/awoo-study.gif

This reverts commit cca7834e6718c6ff64da42ed5e9770880a3e8ff6.

### CODE REVIEW

**Comment by N-R-K** [comment]
I've had some success with the following patch:

```diff
diff --git a/image.c b/image.c
index 8f6e3a8..1ca6820 100644
--- a/image.c
+++ b/image.c
@@ -202,9 +202,9 @@ bool img_load_gif(img_t *img, const fileinfo_t *file)
 
 			ptr = data = emalloc(sw * sh * sizeof(DATA32));
 			cmap = gif->Image.ColorMap ? gif->Image.ColorMap : gif->SColorMap;
-			r = cmap->Colors[bg].Red;
-			g = cmap->Colors[bg].Green;
-			b = cmap->Colors[bg].Blue;
+			r = cmap->Colors[MIN(bg, cmap->ColorCount-1)].Red;
+			g = cmap->Colors[MIN(bg, cmap->ColorCount-1)].Green;
+			b = cmap->Colors[MIN(bg, cmap->ColorCount-1)].Blue;
 			bgpixel = 0x00ffffff & (r << 16 | g << 8 | b);
 
 			for (i = 0; i < sh; i++) {
```

But more testing is required.

**Comment by N-R-K** [comment]
I've had some success with the following patch, but only tested on the attached image. Needs more testing.

```diff
diff --git a/image.c b/image.c
index 8f6e3a8..1d8ba81 100644
--- a/image.c
+++ b/image.c
@@ -202,6 +202,7 @@ bool img_load_gif(img_t *img, const fileinfo_t *file)
 			cmap = gif->Image.ColorMap ? gif->Image.ColorMap : gif->SColorMap;
+			bg = MIN(bg, cmap->ColorCount-1);
 			r = cmap->Colors[bg].Red;
```

**Comment by N-R-K** [comment]
From the [gif standard](http://giflib.sourceforge.net/gifstandard/GIF89a.html)

> Background Color Index:
Index into the Global Color Table for the Background Color. The Background Color is the color used for those pixels on the screen that are not covered by an image. If the Global Color Table Flag is set to (zero), this field should be zero and should be ignored.

I think this is what's going on here. I'll add a commit fixing it and see how that goes.

**Comment by N-R-K** [comment]
Took a look into imlib2's gif loader and it says bg should already be transparent black if `bg > ColorCount`.

**Review by XPhyro — COMMENTED** [review]
> ... only tested on the attached image. Needs more testing.

I can confirm this PR fixes viewing that GIF and, so far, does not break others.

I'll wait for other people to see the PR for more testing.

**Review by eylles — APPROVED** [review]

**Review by XPhyro — APPROVED** [review]

**Pull request merged**
