### PR TITLE
always null-terminate on strncpy()

### PR DESCRIPTION
**Pull request by N-R-K**
this introduces xstrncpy() which always null-terminates.

### CODE REVIEW

**Comment by TAAPArthur** [comment]
Not really sold on this PR. Never been a fan of abstracting away command calls. If we want to be safe, we could just have `win.bar.l.size` be one less than the total size of the buffer and leave the final byte the default of zero.

For the current PR, not really sure why memccpy was used instead of strncpy.
```
void xstrncpy(char *dst, const char *src, size_t n)
{
    strncpy(dst, src, n);
    dst[n-1] = 0;
}
```
would work just as well. Always zeroing the final byte seems cleaner than checking to see if we need to.

**Comment by N-R-K** [comment]
> Always zeroing the final byte seems cleaner than checking to see if we need to.

Didn't want to blindly overwrite the last byte unless it was needed. But for our usecase, it shouldn't matter. So I'm fine either ways.

> Not really sold on this PR. Never been a fan of abstracting away command calls.

The standard C string library has been such a disaster that pretty much everyone ends up either reinventing this wheel or using wrappers. But I *do* see people don't like wrappers, since the behavior (as well as the pitfalls) of a standard library function more well understood compared to a custom wrapper.

> If we want to be safe, we could just have `win.bar.l.size` be one less than the total size of the buffer and leave the final byte the default of zero.

This would work, but that means the ritual of subtracting one from the size needs to be performed on each strncpy call, which I'm not a fan of. But given how little strncpy calls we have, maybe this concern isn't valid here.

---

One other option is to use `strlcpy` which should be available on BSD systems, and on linux/glibc systems we'll have to provide a compatibility fallback.

**Comment by N-R-K** [comment]
So what's the verdict on this? I'm fine with using `strlcpy` if that's more preferred over a custom strncpy wrapper.

**Comment by explosion-mental** [comment]
This looks dumb.
Currently there are only 3 calls of `strncpy and 1 call to `strcpy`, if we use the `nop` autoreload backend.

NULL terminating after these calls should be fine.

**Comment by N-R-K** [comment]
> NULL terminating after these calls should be fine.

Having a safe function means we can reuse it in the future if needed, rather than having to remember to manually do it on each new strncpy call we introduce.

> 1 call to strcpy

This seems fine. The basename will always be shorter than the fullpath.

https://github.com/nsxiv/nsxiv/blob/7fb8a61c47b8968f3da7decaefbe55b621e68420/autoreload_inotify.c#L75-L81

**Comment by explosion-mental** [comment]
a bit Xtreme for this.
You know C funcs, u need to check for stuff.

**Comment by explosion-mental** [comment]
I see no downsides.
Since it's not used much, what about a longer/descriptive name?

**Comment by N-R-K** [comment]
I suppose using `strlcpy` will be less controversial then? @TAAPArthur

**Comment by TAAPArthur** [comment]
So we are just stealing the function from BSD? I feel like that is more trouble than its worth. Creating the buffer to always be 1 larger than the max value of size fixes the problem with less trouble. Or using `size - 1` whenever we want to use strncopy. If we don't like either of those then we could always just force the last byte to be 0.

Guess I should try to be more objective than just saying it feels ugly. What about if a user wants to use `-lbsd` to achieve some goal in their config.h? Won't they have symbol collisions. They could in theory do so without patching and we could just break that usecase. I know that protecting such cases isn't the goal, but I feel we are adding complexity to fix a possible edge case that so happens to make nsxiv less extensible when there are simpler/safer solutions.

I don't have that strong of an objection, but adding 3 chars to 3 lines seems much better than adding/copying an entire file

**Comment by N-R-K** [comment]
> So we are just stealing the function from BSD? I feel like that is more trouble than its worth. 

BSD license grants the permission to use and modify it, I wouldn't call it "stealing".

> Creating the buffer to always be 1 larger than the max value of size fixes the problem with less trouble.

I'm sorta against this. It's won't be immediately obvious from looking at the `strncpy` call that `size` is actually +1. It also makes the size a bit misleading.

> using size - 1 whenever we want to use strncopy. If we don't like either of those then we could always just force the last byte to be 0.

Would've preferred having a safer function rather than manually doing it per call. But if manually doing it avoids the controversy with a wrapper function then I guess I'll have to content with that.

**Comment by N-R-K** [comment]
Looks like we're already allocating `+3` due to the utf8 decoder being used.

https://github.com/nsxiv/nsxiv/blob/3a22e6a6c5ad10e8c5cb9abb3615d2a8867d63e9/window.c#L153-L157

**Comment by N-R-K** [comment]
Looking back, we're using `malloc` and not `calloc` so the memory region isn't guaranteed to be 0. This kinda makes me question why we're using malloc to begin with, because the size of the buffer seems to be static.

https://github.com/nsxiv/nsxiv/blob/3a22e6a6c5ad10e8c5cb9abb3615d2a8867d63e9/window.c#L151-L153

**Comment by N-R-K** [comment]
> This kinda makes me question why we're using malloc to begin with

In any case, I think that's for another time. There shouldn't be any harm in making sure all the string-copies are properly null-terminated right at call site.

**Comment by N-R-K** [comment]
Thinking back, the problem at our hand is that we're trying to copy a c-string into a fixed size buffer and truncate (properly, null-terminated) if it's too big.

`strncpy` is definitely not the right function for this because it neither truncates properly nor does it *just* copy the string; it goes on to pad `dest` with useless zeros:

> If the length of src is less than n, strncpy() writes additional null bytes to dest to ensure that a total of n bytes are written.

With that, I'm now firmly against (ab)using `strncpy` all together.

The only *established* interface that I'm aware of which does what we want is [strscpy](https://www.kernel.org/doc/htmldocs/kernel-api/API-strscpy.html). Implemented a trivial version of it at 33b0e3f.

**Pull request closed without merging**
