### PR TITLE
Adding shields.io badges for Readme

### PR DESCRIPTION
**Pull request by WitherCubes**
This is not a very useful merge, but it adds shields.io badges to the Readme just for asthetics.

### CODE REVIEW

**Comment by N-R-K** [comment]
The green color doesn't seem too readable. Can you try "dark-green" or something like that?
Also personal opinion, not a fan of pink, would prefer orange or maybe red instead.
image

**Comment by WitherCubes** [comment]
I will change the colors and squash the commits.

**Comment by N-R-K** [comment]
Squashing isn't needed, we can squash the PR when merging it via github ui.

**Comment by WitherCubes** [comment]
Ok, changed up the colors:
image

**Comment by N-R-K** [comment]
Looks better, one other option would be `lightgreen`



---

@XPhyro what do you think about this PR? I'm personally neutral towards it.

**Comment by N-R-K** [comment]
One more thing, could use the LoC instead of code-size

**Review by N-R-K — APPROVED** [review]

**Review by eylles — APPROVED** [review]

**Comment by eylles** [comment]
how about adding a link to the online manpage with a shield?

**Comment by N-R-K** [comment]
How reliable are these badges? The LoC shows up as "invalid" for me.

image

**Comment by WitherCubes** [comment]
> How reliable are these badges? The LoC shows up as "invalid" for me.
> 
> image

I haven't had any issues with it, it always loaded and had no issues.

**Comment by N-R-K** [comment]
> I haven't had any issues with it, it always loaded properly.

Seems to be working fine now. Could've been an issue on my end, not sure.

**Comment by eylles** [comment]
squashed and merged.

**Pull request merged**
