### PR TITLE
reduce calls to win-title when there's no change

### PR DESCRIPTION
**Pull request by N-R-K**
Closes: https://github.com/nsxiv/nsxiv/issues/258

### CODE REVIEW

**Comment by N-R-K** [comment]
Not a fan of functions retaining static state or comparing pointers like this. But we can't dereference this because the pointer/file might've already been removed.

The other option is to hunt down all the functions that may change the selected file and/or zoom level and move the call to `win_set_title()` in there (which I'm admittedly not a fan of either).

**Comment by N-R-K** [comment]
I'm having a hard time figuring out if the current state of the PR is better than https://github.com/nsxiv/nsxiv/pull/266/commits/11b5e021963b0bfa09f5f91a57994ba45b7b6dad or not.

But in any case, even if we reduce calls to win-title, the problem that it blocks nsxiv still remains. To reproduce, try adding `sleep 1` in the `win-title` script and running nsxiv.

I'm thinking a proper solution is to give it similar treatment as `image-info` and poll on it so we don't get blocked.

**Comment by TAAPArthur** [comment]
Mentioned this in #271, but would it be better to just have a dirty bit and make win_set_title a no-op if it isn't set. (need to double check but perhaps img->dirty/tns->dirty would work sufficiently well for this). If not we'd just need to set the bit every interesting point which I believe would just be file loading given the current state of master. 

Also not sure if it matters, but with this PR as is we wouldn't set the title on window resize/map.

**Comment by N-R-K** [comment]
Having a dirty flag seems fine. But that doesn't solve the problem that the script can freeze nsxiv's UI. And while we could just ask users to make their script fast, it's still not a great that it's possible to begin with. Especially since we already have the machinary to avoid getting blocked.

> I don't think I understand. Don't we wait somewhere and read all of the process stdout? As long as nsxiv is single threaded, we'll block somewhere.

We only read it once we're confirmed via `select/poll` that there's data to be actually read.

https://github.com/nsxiv/nsxiv/blob/3a22e6a6c5ad10e8c5cb9abb3615d2a8867d63e9/main.c#L738-L741

Adding a `sleep 1` in `image-info` for example, nsxiv still works just fine, while adding a sleep to `win-title` freezes everything.

**Comment by N-R-K** [comment]
> but with this PR as is we wouldn't set the title on window resize/map.

Thanks, missed that. Fixed it on a branch I'm playing around on with the `title_dirty` idea while also make sure we don't get blocked on `read`. I'll open a separate PR (or maybe force push here) once I'm done.

**Comment by N-R-K** [comment]
One other thing #275 did was that it simplified `win_set_title` and got rid of the weird `init` dance. Didn't hear any objection towards that change, so figured I'd push it here.

**Review by TAAPArthur — APPROVED** [review]

**Pull request merged**
