### PR TITLE
Update thumbnail and compress images

### PR DESCRIPTION
**Pull request by XPhyro**
Updated the thumbnail preview to show the different configuration options available.

Should I shrink the resolution? It is currently 1920x1080.

### CODE REVIEW

**Comment by N-R-K** [comment]
Keep it 1080p, but compress it more. 800+kb is too much, aim for 300kb.

Also a couple request.

* Can the thumbnail sizes be any bigger? I'd like them to be the biggest size.
* Put he white bg logo where the pepe is (right-top)
* Put the black bg logo where the while bg is (bottom-mid)
* Put the pepe to where the black bg logo is (bottom-right)

Also bit of a personal preference, but i'd like the pepe to be updated to this instead (maybe flip it horizontal so he's facing the left size) :

basedpepe

**Comment by XPhyro** [comment]
Thumbnails are the biggest size in the default array. I can modify the array and make them even bigger.

**Comment by N-R-K** [comment]
> Thumbnails are the biggest size in the default array. I can modify the array and make them even bigger.

Do it. Also I tried to compress the current image and it looks too bad if we aim of <300kb. Drop the res to 720p.

**Comment by XPhyro** [comment]
I also want to put a tux somewhere, should it go above pepe?

**Comment by N-R-K** [comment]
Drop the black (icon) logo then. I think the white one is more pleasing anyways. Also which tux you want to put? The vanilla one?

**Comment by XPhyro** [comment]
This one

Tux svg

**Comment by N-R-K** [comment]
Imo, a bit too vanilla. What about this one

image

**Comment by XPhyro** [comment]
I think this one is a bit too non-vanilla. Maybe something in the middle?

**Comment by N-R-K** [comment]
Btw, how's sxiv in the bsd world? If it's used there as well, then idk if we want to have tux on the preview.

**Comment by XPhyro** [comment]
It currently looks like this with the vanilla one. It's 560 KB after compressing with [zImageOptimizer](https://github.com/zevilz/zImageOptimizer) (a meta optimizer that uses many optimizers).

I could probably get this down a lot with lossy compression.

> Btw, how's sxiv in the bsd world? If it's used there as well, then idk if we want to have tux on the preview.

I have no idea.

thumb

**Comment by N-R-K** [comment]
I think that looks good. The size is a bit of a problem though. The old thumb was `26kb` :D

Also if we're going for THE C book theme, then remove all the images that don't have THE C book from there.

Here's one, add it to the collection:


cirno likes C

**Comment by XPhyro** [comment]
I'll see how much I can get it down with lossy compression. So far I only used lossless.

I went for a C/Assembly/Compiler/Mathematics... collection. I could go for a C or K&R only collection.

**Comment by N-R-K** [comment]
On the `logo` can you use the `image-info` to show the res in the status bar as well?

image

**Comment by N-R-K** [comment]
Also scale the pepe so that there's no gap (blue)

image

**Comment by XPhyro** [comment]
There might be a bug with nsxiv, it does not call `image-info`.

I'll use sxiv on the logo image for now.

**Comment by N-R-K** [comment]
> There might be a bug with nsxiv, it does not call `image-info`.
> 
> I'll use sxiv on the logo image for now.

Are you sure? It needs to be under  `~/.config/nsxiv/exec`  if you're on the rename branch.

**Comment by XPhyro** [comment]
Here it is. Increased thumbnail sizes and removed tux.

The top-right one is sxiv as nsxiv did not recognise `image-info`.

**Comment by N-R-K** [comment]
> Compiled from the rename branch, and the file is in `~/.config/nsxiv/exec`. It's not recognised.

`dev` branch works fine. Looks like we missed something on the rename PR. I'll take a look.

**Comment by N-R-K** [comment]
The flipped pepe actually looks very bad. Switch back to having pepe - tux in the bottom. One logo is enough.

Also drop the resolution to 800x600. That should be enough for being embedded in the README.

**Comment by XPhyro** [comment]
The `image-info` bug is fixed.

-----

I'll drop the resolution to 1152x648 and apply lossy compression. It should go down quite a lot.

**Comment by N-R-K** [comment]
Did you upload the lossy or lossless version? Looks good to me.

**Comment by XPhyro** [comment]
I uploaded the raw version for faster iteration.

Since you approved it, I'll process it now.

**Comment by XPhyro** [comment]
shrank to 1036x582, applied lossless + (some) lossy compression
393 KB

thumb-lossy

**Comment by N-R-K** [comment]
hmm.. would've preferred <300kb but the quality already looks kind a scuffed. I think it's fine. :+1: 

Let's wait for what others have to say @GRFreire @TAAPArthur @eylles

**Review by N-R-K — APPROVED** [review]

**Comment by TAAPArthur** [comment]
Thanks for the ping, but I'm kinda indifferent. Some part of me is questioning the >300KB image, but don't think it really matters outside of principle. 
Also the last image posted could give the impression that that is a single instance of nsxiv instead of 4 separate ones. Maybe have a foot note if we don't already

**Comment by N-R-K** [comment]
I guess we can also put gaps around the windows, that way it would be clearer that the top is actually the wm bar and not nsxiv bar.

**Comment by XPhyro** [comment]
Noted down the gaps. I'll wait some time to redo the image to get more feedback. It'll be easier to apply them in batch.

**Comment by eylles** [comment]
welp, only waiting for the gaps to be added for better clarity i think this is good.

**Review by eylles — APPROVED** [review]

**Comment by XPhyro** [comment]
thumb

**Pull request merged**
