### PR TITLE
Merge `dev` to `master`

### PR DESCRIPTION
**Pull request by XPhyro**
Merge branch `dev` to `master`.

Let's also remove `dev` branch after this PR per [this discussion](https://github.com/nsxiv/nsxiv/discussions/17#discussioncomment-1309536).

### CODE REVIEW

**Comment by N-R-K** [comment]
We could also wait until release, but since the main point of `dev` was to wait till rename, I'm okay merging this.

On a sidenote, I think it might be beneficial to update our master for visibility reasons since currently it looks like nothing has been done.

**Review by N-R-K — APPROVED** [review]

**Comment by XPhyro** [comment]
#9 already bumped the version, the commit in `dev` is tagged with v27 and the changelog includes a v27 with a lot of entries. I think we can proceed with the merge, and say the following patches are in v28.

----

And yes, the readme is quite problematic on master.

**Review by eylles — APPROVED** [review]
Now that the bulk of the work needed before the rename is done and we are so close to a release i think this should be merged to master as soon as possible, specially for visibility reasons.

**Comment by N-R-K** [comment]
> #9 already bumped the version, the commit in `dev` is tagged with v27

We can clear the tag. Also https://github.com/nsxiv/nsxiv/pull/55 this should be worth merging before release.

**Comment by N-R-K** [comment]
@XPhyro  I've deleted the tag. We should merge #55 first before tagging. I'll clean some more things up there.

**Comment by XPhyro** [comment]
Okay.

Since we agree on the visibility issue, I'm merging this.

**Comment by N-R-K** [comment]
The doc_cleanup_went into `dev`

**Comment by eylles** [comment]
lol another merge to do :DDDDDD

**Comment by XPhyro** [comment]
:D 
I'll just re-push it to `master`

**Comment by XPhyro** [comment]
Done. I'll also remove `dev` per [this comment](https://github.com/nsxiv/nsxiv/discussions/17#discussioncomment-1309536).

I'm assuming the verdict has not changed, yes?

**Comment by N-R-K** [comment]
Yeah, remove dev.

**Pull request merged**
