### PR TITLE
Cleanup Docs

### PR DESCRIPTION
**Pull request by N-R-K**
For cleaning up anything we might've missed in the rename PR.

You can preview how everything renders over here: https://github.com/N-R-K/nsxiv/tree/my_docs_cleanup

Note that the `#n` links won't work since it's a different repo.

### CODE REVIEW

**Comment by eylles** [comment]
seems good enough for now as there are still things to do before a release.

**Review by eylles — APPROVED** [review]

**Comment by N-R-K** [comment]
Not under any hurry to merge this. I'd rather have everything cleaned up here at once than have to open more PRs.

**Comment by eylles** [comment]
so this is intended to be merged after the other PRs for the additional resources right? or will this be merged after the dmenu mode?

**Comment by N-R-K** [comment]
Most changes here will be on README and CHANGELOG, maybe the manpage. So I don't think it matters when this gets merged.

As for the dmenu mode, I fine delaying it for next release. I'd rather not merge it prematurely and then realize that we didn't think through some edge-case.

**Review by Ytrewq13 — COMMENTED** [review]
I think the line in README.md:

> $ make PREFIX="/your/dir" install

should be changed to:

> \# make PREFIX="/your/dir" install

Because installing to a custom directory would still need root permissions unless it's a user directory.

Does the directory being `/your/dir` imply that the user has permissions for the directory?

**Comment by N-R-K** [comment]
That depends on the PREFIX, if someone wants to install to `~/.local/bin/` then root permission wouldn't be needed. So I think it's fine as is.

**Review by Ytrewq13 — APPROVED** [review]

**Comment by N-R-K** [comment]
@XPhyro I'll open a new pr
also I'll change the v27 to git, since that link is not valid in CHANGELOG.

**Comment by XPhyro** [comment]
Sure, I'll unpush the commit.

**Comment by N-R-K** [comment]
nah, don't

**Comment by N-R-K** [comment]
ahh well, too late :D

**Comment by XPhyro** [comment]
I can repush it :D

**Comment by N-R-K** [comment]
No pls :D

**Pull request merged**
