### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by XPhyro**

### CODE REVIEW

**Review by N-R-K — APPROVED** [review]

**Comment by N-R-K** [comment]
@XPhyro I merged this prematurely.
https://github.com/XPhyro/nsxiv/tree/rename
The background here isn't transparent and looks horrible on dark theme.

image

**Comment by XPhyro** [comment]
I just added an `n` in front of the previous logo. Do we go for different colours? Maybe black background and white text? It would look decent on light theme too, I imagine.

**Comment by N-R-K** [comment]
Wasn't the old logo transparent?

**Comment by XPhyro** [comment]
Turns out I saved without transparency. I'll force push to `gh-pages`.

**Comment by XPhyro** [comment]
Done.

logo

**Comment by N-R-K** [comment]
@XPhyro Idk if we can reopen a PR after it being merged. Can you just commit the new version straight into https://github.com/nsxiv/nsxiv/tree/gh-pages the gh-pages branch?

**Comment by XPhyro** [comment]
The current one should be transparent.

**Pull request merged**
