### PR TITLE
Change location of example scripts

### LINKED ISSUE #85: Changing the location of example scripts
As discussed here https://github.com/void-linux/void-packages/pull/33009#issuecomment-924334800 , should we change our example script location from `$(DESTDIR)$(PREFIX)/share/nsxiv/exec/` to `$(DESTDIR)$(PREFIX)/share/examples/nsxiv` ?

### PR DESCRIPTION
**Pull request by XPhyro**
Changed the location of example scripts from `$(DESTDIR)$(PREFIX)/share/nsxiv/exec/` to `$(DESTDIR)$(PREFIX)/share/doc/nsxiv/examples/`.

Closes #85.

### CODE REVIEW

**Comment by N-R-K** [comment]
If this is just a void specific thing, then I don't think we should change it. Especially since we try to stay close to sxiv as much as possible.

**Comment by XPhyro** [comment]
Changed the location to `$(DESTDIR)$(PREFIX)/share/doc/nsxiv/examples/`.

**Review by N-R-K — APPROVED** [review]

**Comment by N-R-K** [comment]
Since we're offering a `DOCPREFIX` which distros can change easily, should we keep the `share/nsxiv/exec` default or change it?

**Comment by XPhyro** [comment]
I think we can change the default to the conventional approach.

**Review by GRFreire — APPROVED** [review]

**Pull request merged**
