### PR TITLE
Changing relative links to absolute links in README

### PR DESCRIPTION
**Pull request by WitherCubes**
This is a fix for the broken links when generating the website. See #161

### CODE REVIEW

**Review by eylles — APPROVED** [review]

**Comment by GRFreire** [comment]
I'm ok with these changes, but here is some food for thought:

The nice thing about relative links is that forks don't have to change the links to point to their repos (and being on a different head comparing to upstream because of that). Maybe using `sed` while creating the `html` files to replace the relative path to the absolute link? Idk.

**Review by GRFreire — APPROVED** [review]

**Comment by N-R-K** [comment]
> Maybe using sed while creating the html files to replace the relative path to the absolute link?

Any suggestions on how the logic of that should be? I'm thinking we can match `[.*](.*)` and check if `(` is immediately followed by "http" or not.

Not sure how reliable that is or if there's going to be false positives. @WitherCubes can you give this a try?

**Comment by WitherCubes** [comment]
I will give it a try.

**Review by N-R-K — CHANGES_REQUESTED** [review]
Should adjust the script instead, see: https://github.com/nsxiv/nsxiv/pull/168#issuecomment-974530034

**Comment by mamg22** [comment]
Would the [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) HTML element help fix the relative paths? I found it after looking for alternatives to pre-processing the markdown files with `sed` or post-processing the html files. To me it seems like a more reliable solution, however, I haven't tested it yet.

**Comment by N-R-K** [comment]
> Would the <base> HTML element help fix the relative paths?

Looks interesting. Should be much easier than trying to manually replace the links.

**Comment by mamg22** [comment]
After some testing (on qutebrowser + QtWebEngine), it seems that the `<base>` does work, but has a few gotchas:

* It takes effect only on elements after it, so stylesheets, scripts and other resources that aren't on the new base url should be put before the `<base>`.
* However, `<link rel="icon">` even when placed before the `<base>` still used the new base url to get the icon. Though this shouldn't be an issue because the new script uses an absolute path for the icon.

**Comment by WitherCubes** [comment]
> * It affects [in-page anchors](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#in-page_anchors), loading the page again instead of just jumping to the anchor.

I think this page doesn't use any in-page anchors, can you explain further more?

**Comment by mamg22** [comment]
That was just highlighting one more gotcha of that element, as you said, it doesn't affect the current page.

It could conflict with things like the navigation sidebar suggested in [#161 (comment)](https://github.com/nsxiv/nsxiv/pull/161#issuecomment-962502595).

**Comment by WitherCubes** [comment]
The navigation sidebar is not for now, we can come up with a solution later, or just drop the idea of having a navigation sidebar. It is just my opinion.

**Comment by N-R-K** [comment]
Closing this since we're using `<base>` tag in https://github.com/nsxiv/nsxiv/pull/161/commits/857544e4ebf807616e3ed3f799ccbe080c296e92

**Pull request closed without merging**
