### PR TITLE
Keybinding fallthrough

### PR DESCRIPTION
**Pull request by TAAPArthur**
**This PR isn't intended to change default behavior.**

This PR does 2 things
* adds an new config option `abort_on_binding_match` to allow users to abort key/mouse binding processing once a match is found and preservers current behavior by default.
* modifies nsxiv so that all keybindings continue to work as expected regardless of the value of `abort_on_binding_match`

For why this is useful see #108 options (1) and (4) -- basically it makes nsxiv more extensible to some future features/external patches

### CODE REVIEW

**Comment by N-R-K** [comment]
Moving to here to not clog up #148 .

So let's pretend that we've accepted that "source users are our main target but we still care about not breaking default for binary users." In that case this PR would be valid.

But what's stopping me from ripping out all the directory loading functions? They're about 100~ LoC and can be done in one shell line `find . -type f | sxiv -i`. In fact it can be done _more reliably_ via `find . -type f -print0 | xargs -0 sxiv`.

If source based users are the primary target then ripping out dir loading will be 100x more valid than this PR as it will remove massive amount of code and reduce complexity.

If you ask me, this will be an even worse situation, because there are many more things which I can think we should be able to completely remove (key-handler comes to mind) and be perfectly valid if source/power users are our primary target.

@TAAPArthur Do you see why we can't have it both ways?

**Comment by TAAPArthur** [comment]
No. 

>But what's stopping me from ripping out all the directory loading functions?

It would break default behavior for source or binary users. 

If you mean to say that focusing on people who will customize nsxiv is at odds with keeping existing defaults, I agree. In the sense that we could reach a better ideal if forgo defaults. On the flip side, if I'm a user (source or binary) and am used to pointing nsxiv to a directory maybe I don't want that to suddenly break.

My point is that even if everyone built from source, breaking defaults could still be annoying and not something I think we should do carelessly. I think it would be more annoying if nsxiv was heavily customized/patch. Needing to resolve conflicts when trying to upgrade isn't ideal; even worse if you don't notice the broken functionality at build time. 

This PR is a great example because if you had customization that relied on the fall through behavior, you could get drastically different behavior at runtime.

I'm not saying we should or need to keep the defaults or not. I just feel like keeping the defaults and focusing on source users aren't mutually exclusive.

>If source based users are the primary target then ripping out dir loading will be 100x more valid than this PR as it will remove massive amount of code and reduce complexity.

More valid in an ideal sense but also much more noticeable and prone to controversy.

**Comment by N-R-K** [comment]
> If you mean to say that focusing on people who will customize nsxiv is at odds with keeping existing defaults, I agree

Yes, that was the point. We're trying to sit on both sides of the fence and have things both ways.

We can make up a hundred rules, but one can still interpret it in different ways depending on their personal agenda. If we can have a clear stance on who the target audience is, then there wouldn't be a need to define new rules each week, the "rules" and arguments would arise automatically from that target audience.

But if we want to sit on both sides of the fence then we're going to have to keep making new rules every week because no amount of rules are going to stop these "philosophical" conflicts when the target audience isn't crystal clear.

**Comment by TAAPArthur** [comment]
I mean this is where we disagree. I don't think just deciding about source vs binary users would help anything. I also feel like you're criticism is coming too early as we haven't (yet?) applied any new rules so haven't had a chance to make new ones up each week. If we say the target audience is X it and that helps you state what the rules should be great. My point is deciding on that won't magically align all of us. Great example would be keeping existing behavior as explained earlier. Making a statement like we are fine breaking arbitrary customization seems far more helpful since it can directly apply to PRs where that was a point of contention

I also think the terminology you are using isn't helpful. binary vs source isn't the main point right? Isn't it people who will customize vs who won't?

**Comment by N-R-K** [comment]
> I don't think just deciding about source vs binary users would help anything.

We'll just have to agree to disagree then.

> binary vs source isn't the main point right? Isn't it people who will customize vs who won't?

We can use `power user` vs `basic user` if that's more helpful. But the underlying point remains the same.

> I also feel like you're criticism is coming too early as we haven't (yet?) applied any new rules so haven't had a chance to make new ones up each week.

Not yet, but it's not hard (for me at least) to see that happening. And from this comment https://github.com/nsxiv/nsxiv/issues/148#issuecomment-960581717 of @bakkeby 's , I'd assume he also thinks the same.

> I am only focusing on the target audience / target user group here because there should be a red thread throughout the project goals and scope such that all the restrictions, or things we are open to, make sense and are aligned in the broader perspective. If the target audience is anyone and everyone then the rest of the points merely feels like hand picked and subjective limitations driven by our own personal agendas.

**Comment by TAAPArthur** [comment]
I get a different impression from that comment.

Correct me if I'm wrong, but you want to use the audience as a guide to set the rules while I want to set the rules directly where rules rules are probably biased to a specific audience. The rules end up getting set either way which is the goal I'm after. I just want to make sure we spell out whatever rules our target audience may imply

**Pull request closed without merging**
