### PR TITLE
fix: unable to use XK_Escape in keybindings

### PR DESCRIPTION
**Pull request by XPhyro**

### CODE REVIEW

**Comment by N-R-K** [comment]
I don't really see much benefit of this tbh. Feels like something that should be done on a personal build instead.

**Comment by XPhyro** [comment]
> I don't really see much benefit of this tbh.

The issue referenced in #78 (https://github.com/muennich/sxiv/pull/428) had a problem with not being able to send <kbd>Escape</kbd>. The resolution was tending towards a key-handler rework, which I am not fond of, so this should solve that aspect.

> Feels like something that should be done on a personal build instead.

I think we can at least not hard-code the value to make it easy to change or find what to change on personal builds.

**Comment by N-R-K** [comment]
The main problem was that you cannot bind anything to <kbd>Escape</kbd>, with this the problem remains.
If one sets `handler_abort_key` to `q`, he now won't be able to bind anything else to `q`.

**Comment by XPhyro** [comment]
That was the intention. I think a cancel key should remain.

If one does not want a cancel key, they can just set the cancel key to null. If one wants a different cancel key than <kbd>Escape</kbd>, they can set it to that.

**Comment by N-R-K** [comment]
Imo the proper solution would be make it so

* If key-handler is running and you press `esc`, abort key-handler
* Otherwise `esc` can be bound to anything else like normal

**Comment by XPhyro** [comment]
I just noticed from your comment that the cancel key cannot be bound in nsxiv.

I was talking about sending the <kbd>Escape</kbd> key to the key handler. My intention was to allow the cancel key to be configurable, not to allow that key to be bound in nsxiv, which I did not even know was an issue.

**Comment by XPhyro** [comment]
The current state fixes the in-nsxiv binding issue, but the <kbd>Escape</kbd> key still cannot be sent to the key handler.

I believe this key should be exposed in config.h.

**Comment by N-R-K** [comment]
I think this should solve the problem. We now only look for XK_Escape when key-handler is running, so otherwise Escape can be bound to anything else like normal.

**Comment by N-R-K** [comment]
>  Escape key still cannot be sent to the key handler

What's the usecase for sending Escape to key-handler? Why not send something else?

**Comment by XPhyro** [comment]
> explicitly checking for XK_Escape means the user can't bind any commands to the escape key (i prefer to bind esc to 'exit without output' if possible).

As I just learned about the in-sxiv binding issue, I thought this meant that they could not bind it in their key-handler.

I do not have any use cases for this myself, so I am now content with the current state.

**Review by N-R-K — APPROVED** [review]

**Comment by N-R-K** [comment]
@XPhyro `False` is defined on Xlib. Also as you've said on the other PR, all style/consistency issues should be handled on a separate PR on the whole code-base.

**Comment by N-R-K** [comment]
And if we want to change it here, then we need to change it here too

https://github.com/nsxiv/nsxiv/blob/0e7ab7e5c369e61359951a66a4f02d8062d9a3a3/main.c#L594

Funny enough, here on commands.c we're using the typical stdbool instead of the Xlib `True`

https://github.com/nsxiv/nsxiv/blob/0e7ab7e5c369e61359951a66a4f02d8062d9a3a3/commands.c#L117

**Comment by XPhyro** [comment]
> @XPhyro `False` is defined on Xlib. Also as you've said on the other PR, all style/consistency issues should be handled on a separate PR on the whole code-base.

This seemed close enough, but yes, you're right.

**Comment by TAAPArthur** [comment]
May I throw the wild suggestion out there to just not special case Escape, have a function to clear the var and then have a default binding to call said function when escape is pressed. Won't break anything and will give maximum flexibility.

I'd argue that it is a bug that Escape won't work as a keybinding by default and know one would know unless they looked at the code.

**Comment by N-R-K** [comment]
> have a function to clear the var and then have a default binding to call said function when escape is pressed

I am not quite sure I follow. Can you elaborate a bit more?

**Comment by TAAPArthur** [comment]
So right now Escape is hardcoded in on_keypress to provide some functionality which is why it can't be used in keybindings. The functionality is just `extprefix = False;`. I'm proposing to just make a keybinding which just just sets extprefix to false and by default make Escape bind to it. If someone wants to change what Escape does, they just have to change the binding.

**Comment by N-R-K** [comment]
> So right now Escape is hardcoded in on_keypress to provide some functionality which is why it can't be used in keybindings. The functionality is just `extprefix = False;`. I'm proposing to just make a keybinding which just just sets extprefix to false and by default make Escape bind to it. If someone wants to change what Escape does, they just have to change the binding.

I see. Well, in that case if someone changes Escape then they'll need to also bind something else to `extprefix = false`.

Imo having `Esc` cancel keyhandler makes sense as a keybinding and currently (in this PR https://github.com/nsxiv/nsxiv/pull/91/commits/350a81bba2b4991869fd861ca392b6368116a93c) you can bind `Esc` like any other key. The check will only happen if `extprefix` is true.

**Comment by N-R-K** [comment]
> So right now Escape is hardcoded in on_keypress to provide some functionality which is why it can't be used in keybindings. The functionality is just `extprefix = False;`. I'm proposing to just make a keybinding which just just sets extprefix to false and by default make Escape bind to it. If someone wants to change what Escape does, they just have to change the binding.

Tried it out, seems like it won't be as simple as described. By having a function `cg_abort_keyhandler` which just sets `extprefix` to false, it also ends up sending that key to the key-handler itself.

**Comment by N-R-K** [comment]
@TAAPArthur Currently keybindings have the least priority.

https://github.com/nsxiv/nsxiv/blob/0e7ab7e5c369e61359951a66a4f02d8062d9a3a3/main.c#L590-L599

Which is why just having a function that sets `extprefix` to false won't work. Do you have any way to combat that?

**Comment by N-R-K** [comment]
I guess we can just do this https://github.com/nsxiv/nsxiv/pull/91/commits/dc0ce789185cd002a499af5eea9f7f38caa39656 if we want to make the key configurable via `config.h`. Personally I don't see why anyone would want to change away from `esc` but I'm not really against this. Seems like a small change.

**Comment by N-R-K** [comment]
Since these are two different commits doing two separate things, let's not squash this when merging. @XPhyro

**Review by TAAPArthur — APPROVED** [review]

**Pull request merged**
