### PR TITLE
'Automatic' way of setting a cache size

### PR DESCRIPTION
**Pull request by explosion-mental**
Had this idea that I wanted to share. Still a draft since I would prefer an option on the make file to calculate this like `make cachesize`. Also please suggest a different percentaje of the ram, whether to calculate this on `MemTotal` or `MemFree`, etc.

### CODE REVIEW

**Comment by N-R-K** [comment]
I don't think putting cache size in the makefile makes sense tbh. The makefile is for configuring compile time deps.

**Comment by explosion-mental** [comment]
No idea where this could go, since its a one time operation..

**Comment by N-R-K** [comment]
I'm not sure if doing automatic detection at compile time is a good idea to begin with.. At runtime, maybe.

But doing this in compile time probably creates more problem, what if the binary was compiled on a machine with 64gigs of ram and then that binary is distributed via some repo. All the users will end up getting a cache size of the build machine instead.

**Comment by explosion-mental** [comment]
Yeah thats why I would prefer a make option such as `make autocachesize` , meaning that only the user..


Thinking it back, this can be done as an Xresources variable, since thats where most bin users configure it.

**Comment by N-R-K** [comment]
Xresources would be better than doing it in makefile, yes. But I don't think that's a good idea either. Currently, we're using xresources only during `win_init` and only for visuals (font and colors).

If we add Xresources for cache size, then it would be expected to add Xresouces for all the config.h variables as well...

**Comment by explosion-mental** [comment]
hmm not really since most options have a CLI flag or/and a keybinding.

I will make an exception for this being on xresources (about only visuals), since this will 'resolve' the discussion of whether cache size should be changed or not

**Comment by explosion-mental** [comment]
There is already a best way done in #184 for the 'automatic cache size'.

**Pull request closed without merging**
